export * from './approvals'
export * from './auth'
export * from './credentials'
export * from './legends'
export * from './teams'
export * from './projects'
export * from './pending-share'
export * from './interviews'
export * from './payment-requisites'
export * from './money'
export * from './users'
export * from './finance'
export * from './edit-cascade'
export * from './admin'
export * from './audit-log'
export * from './view-permissions'
export * from './admin-actions'
export * from './documents'
export * from './invoices'
export * from './notifications'
export * from './contracts'
export * from './employee-contracts'
export * from './tos'
export * from './onboarding'
export * from './vacancies'
export * from './resume'
export * from './telemetry'
export * from './contact'
export * from './csp-report'
export * from './job-sourcing'

// Hardcoded partner user IDs (stable across environments).
// Valid RFC 4122 v4 UUIDs — must match migration 0028_admin_uuid_normalize.sql
// and apps/api/src/database/seed.ts constants.
export const MAKSYM_ID = 'a8f4d3b1-c2e5-4a1f-9b3d-8c7e6f5a4b21'
export const KOSTYA_ID = 'b9e5c4d2-d3f6-4b2e-ac4e-9d8f7a6b5c32'
