#!/bin/bash
# ECC stable id: pre:bash:prettier-gate
#
# Purpose: block `git push` when PR-changed files contain formatting that
# `prettier --write` would have corrected. Local mirror of the CI check
# `.github/workflows/check-no-skip-hooks.yml` (job check-formatting), moved to
# the pre-push surface so unformatted agent commits are caught BEFORE they reach
# CI (recurring manual cleanup on PR #259 / #261 / #263, 2026-06-21).
#
# Why a Claude PreToolUse hook (not .husky/pre-push):
#   In a FRESH `isolation=worktree` worktree, `core.hooksPath=.husky/_` points at
#   a directory that does NOT exist (it is gitignored, generated by `husky` during
#   the `prepare` script on `pnpm install`). With no node_modules => no husky =>
#   `.husky/_/pre-commit` and `.husky/_/pre-push` are absent => git SILENTLY skips
#   them. So lint-staged `prettier --write` never runs and the unformatted commit
#   ships. The ac_verified gate that agents "always pass" is NOT husky either — it
#   is the PreToolUse:Bash hook pre-bash-coder-push-gate.sh. This hook lives on the
#   same surface so it is equally unskippable in worktrees.
#
# Contract:
#   - Reads tool-call JSON from stdin.
#   - Fast-exit (0) on every non-`git push` command.
#   - exit 2 + JSON {decision:block, reason} on unformatted files.
#   - FAIL LOUD (block) if prettier cannot be resolved — never silent-skip.
#   - Does NOT touch / weaken the ac_verified gate (separate hook).
#
# Decision tree (after `git push` is detected):
#   - Not in a git work tree                    -> allow
#   - Branch is main / master / HEAD detached   -> allow (we never push there)
#   - origin/main unresolvable (offline first)  -> allow (cannot compute diff)
#   - No changed ts/tsx/js/jsx/json/md/yml files -> allow
#   - prettier binary not resolvable            -> BLOCK (install instruction)
#   - prettier --check passes                   -> allow
#   - prettier --check fails                    -> BLOCK (write instruction)

set -u

CMD=$(python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('command',''))" 2>/dev/null || true)

# Fast exit: not a `git push` invocation at all.
[ -z "$CMD" ] && exit 0
if ! echo "$CMD" | grep -qE '(^|[[:space:]])git[[:space:]]+push([[:space:]]|$)'; then
  exit 0
fi

# Skip `git push --help` / `-h`.
if echo "$CMD" | grep -qE '(^|[[:space:]])(-h|--help)([[:space:]]|$)'; then
  exit 0
fi

# Must be inside a git work tree to enforce.
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0

BRANCH=$(git branch --show-current 2>/dev/null || echo "")
# Detached HEAD or main/master — nothing to format-gate (we never push to main).
[ -z "$BRANCH" ] && exit 0
if echo "$BRANCH" | grep -qE '^(main|master)$'; then
  exit 0
fi

# Resolve the comparison base. Prefer origin/main; fall back to local main.
# If neither resolves (fully offline, no main ref) we cannot compute the PR
# diff — allow the push rather than block on infrastructure we lack.
BASE_REF=""
if git rev-parse --verify --quiet origin/main >/dev/null 2>&1; then
  BASE_REF="origin/main"
elif git rev-parse --verify --quiet main >/dev/null 2>&1; then
  BASE_REF="main"
else
  exit 0
fi

MERGE_BASE=$(git merge-base "$BASE_REF" HEAD 2>/dev/null || echo "")
[ -z "$MERGE_BASE" ] && exit 0

# Collect changed files of formattable types (mirror CI filter). Three-dot diff
# (merge-base..HEAD) lists only files THIS branch touched, never files changed on
# main after branch-off. --diff-filter=ACMR excludes deletions; the -f guard drops
# any path absent from the working tree (renamed/deleted) so prettier never errors
# on a missing file (CI PR #167 lesson, 2026-06-11).
CHANGED_FILES=()
while IFS= read -r f; do
  [ -n "$f" ] && [ -f "$f" ] && CHANGED_FILES+=("$f")
done < <(git diff --name-only --diff-filter=ACMR "$MERGE_BASE...HEAD" 2>/dev/null \
  | grep -E '\.(ts|tsx|js|jsx|json|md|yml|yaml)$' || true)

# Nothing formattable changed — allow.
if [ "${#CHANGED_FILES[@]}" -eq 0 ]; then
  exit 0
fi

# ── Resolve a prettier binary, worktree-safe ─────────────────────────────────
# A fresh worktree has no node_modules, but it is always attached to the MAIN
# repo via .git/worktrees, and the MAIN repo always carries a full install. Try,
# in order:
#   1. this worktree's local .bin (if the worktree was pnpm-installed)
#   2. the MAIN repo's .bin via git-common-dir parent (the reliable path)
#   3. `pnpm exec prettier` from cwd (only works with a local install)
# FAIL LOUD if all fail — never silent-skip a missing formatter.
PRETTIER=""

WT_TOP=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
if [ -n "$WT_TOP" ] && [ -x "$WT_TOP/node_modules/.bin/prettier" ]; then
  PRETTIER="$WT_TOP/node_modules/.bin/prettier"
fi

if [ -z "$PRETTIER" ]; then
  GIT_COMMON=$(git rev-parse --git-common-dir 2>/dev/null || echo "")
  if [ -n "$GIT_COMMON" ]; then
    # git-common-dir is normally <main-repo>/.git -> parent is the main worktree.
    case "$GIT_COMMON" in
      /*) MAIN_ROOT=$(dirname "$GIT_COMMON") ;;
      *)  MAIN_ROOT=$(cd "$(dirname "$GIT_COMMON")" 2>/dev/null && pwd) ;;
    esac
    if [ -n "${MAIN_ROOT:-}" ] && [ -x "$MAIN_ROOT/node_modules/.bin/prettier" ]; then
      PRETTIER="$MAIN_ROOT/node_modules/.bin/prettier"
    fi
  fi
fi

run_prettier_check() {
  # Print prettier's own report to stderr (visible to the agent), return its code.
  if [ -n "$PRETTIER" ]; then
    "$PRETTIER" --check "${CHANGED_FILES[@]}" >&2
    return $?
  fi
  # Last resort: pnpm exec (needs a local install; may ENOENT in a bare worktree).
  if command -v pnpm >/dev/null 2>&1; then
    pnpm exec prettier --check "${CHANGED_FILES[@]}" >&2
    return $?
  fi
  return 127
}

block() {
  # $1 = reason text
  python3 -c "import json,sys; print(json.dumps({'decision':'block','reason':sys.argv[1]}))" "$1" 2>/dev/null
  echo "[pre:bash:prettier-gate] BLOCK branch=$BRANCH" >&2
  exit 2
}

# FAIL LOUD when no formatter is reachable — do not let unformatted code through.
if [ -z "$PRETTIER" ] && ! command -v pnpm >/dev/null 2>&1; then
  block "🚫 PRE-PUSH BLOCK: prettier недоступен — невозможно проверить форматирование.

Похоже, в этом worktree нет node_modules (свежий isolation=worktree без pnpm install).

Исправь:
    pnpm install            # из корня worktree — поднимет prettier + husky

Затем повтори push. Гейт не пропускает код без проверки формата (см.
.claude/rules/common/git-policy.md, prettier-pre-push-гейт)."
fi

if run_prettier_check; then
  exit 0
fi
RC=$?

# rc 127 = prettier resolved to a missing binary at exec time -> treat as fail-loud.
if [ "$RC" -eq 127 ]; then
  block "🚫 PRE-PUSH BLOCK: prettier не запустился (binary not found).

Исправь:
    pnpm install            # из корня worktree

Затем повтори push (см. .claude/rules/common/git-policy.md)."
fi

# Build the exact fix command using the resolved prettier (or pnpm exec fallback).
FILE_LIST="${CHANGED_FILES[*]}"
if [ -n "$PRETTIER" ]; then
  FIX_CMD="$PRETTIER --write $FILE_LIST"
else
  FIX_CMD="pnpm exec prettier --write $FILE_LIST"
fi

block "🚫 PRE-PUSH BLOCK: изменённые файлы не отформатированы prettier'ом.

Это тот же самый гейт, что CI check-formatting (check-no-skip-hooks.yml) —
ловим ДО push, чтобы PR не краснел. Причина: pre-commit hook (lint-staged ->
prettier) молча пропущен (свежий worktree без husky/node_modules).

Исправь форматирование:
    $FIX_CMD

Затем закоммить изменения и повтори push:
    git add $FILE_LIST
    git commit --amend --no-edit     # или новый commit, сохранив ac_verified:

См. .claude/rules/common/git-policy.md (prettier-pre-push-гейт)."
