-- 0024_pending_cash_confirm.sql
--
-- Drop role - phase 4-B round 2. Cash channel re-architecture.
--
-- Old flow: drop picks recipient admin in the UI → /initiate-cash immediately
-- inserts ADMIN_INCOME_CASH + SENIOR_PENDING_PAYOUT and closes the PAYOUT.
--
-- New flow:
--   1. Drop clicks «Я передал нал админу» (no admin selection in UI).
--   2. /initiate-cash flips the placeholder PAYOUT row to a brand-new
--      `PENDING_CASH_CONFIRM` status and inserts NO cascade rows.
--   3. ACCOUNTANT/ADMIN sees the pending list in /crm/finance and chooses
--      which admin actually received the cash.
--   4. /confirm-cash inserts ADMIN_INCOME_CASH + SENIOR_PENDING_PAYOUT
--      against the chosen admin and flips PAYOUT → PAID.
--
-- This migration only adds the new status to the transaction_status enum.
-- Pure ADD VALUE — strictly additive, no DROP / no UPDATE on existing rows.

--> statement-breakpoint
ALTER TYPE "transaction_status" ADD VALUE IF NOT EXISTS 'PENDING_CASH_CONFIRM';
