/**
 * DocumentCard — single card in the documents grid.
 *
 * Visual stack:
 *   - thumbnail (DocumentImage variant='thumbnail') for image MIME types;
 *     PDFs render the category icon overlay
 *   - filename (cyrillic-preserved original name when available, sanitized
 *     fallback otherwise) — clicking opens DocumentDetailDialog
 *   - size · relative date · uploader name
 *   - row of RBAC-conditional buttons (Скачать, Удалить, Восстановить,
 *     Удалить навсегда)
 *
 * Variant 3 hybrid filenames:
 *   - `originalName` is what we render to the user (Cyrillic / Unicode safe)
 *   - `name` (sanitized ASCII) is used inside the S3 key and as the
 *     download-as filename; the user never sees it directly here
 *
 * RECEIPT-specific bits:
 *   - Soft-delete is forbidden (cascade from the parent transaction).
 *   - A "К транзакции #..." link shows the last 8 chars of the linked tx id.
 */
import { useMemo, useState } from 'react'
import { Link } from '@tanstack/react-router'
import { formatDistanceToNow } from 'date-fns'
import { ru } from 'date-fns/locale'
import {
  Download,
  FileSignature,
  FileText,
  Receipt as ReceiptIcon,
  RotateCcw,
  Trash,
  Trash2,
  UserCircle2,
} from 'lucide-react'
import type { Document, SessionUser } from '@crm/shared'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { cn } from '@/lib/utils'
import { formatBytes } from '@/lib/format-bytes'
import {
  useDeleteDocument,
  useDocumentDownloadUrl,
  useHardDeleteDocument,
  useRestoreDocument,
} from '@/hooks/use-documents'
import { DocumentImage } from './document-image'
import { DocumentStatusBadge } from './document-status-badge'

interface DocumentCardProps {
  doc: Document
  viewer: SessionUser
  /**
   * Click handler for the card preview / filename area. The parent passes
   * a callback that opens the DocumentDetailDialog with this document.
   * Omit to render a non-clickable card (used by tests).
   */
  onOpen?: ((doc: Document) => void) | undefined
}

const RECEIPT_DELETE_TOOLTIP = 'Чек удаляется вместе с транзакцией'
const INVOICE_DELETE_TOOLTIP = 'Инвойс удаляется вместе с транзакцией'

/**
 * Extract the 8-char transaction-id prefix that InvoicesService.uploadInternal
 * stamps onto every INVOICE document's name (`invoice-<8chars>.pdf`). Returns
 * null when the filename doesn't match — defensive, never throws.
 */
function extractInvoiceShortId(filename: string): string | null {
  const m = filename.match(/^invoice-([0-9a-f]{8})\.pdf$/i)
  return m && m[1] ? m[1] : null
}

function shortId(id: string): string {
  return id.length > 8 ? id.slice(-8) : id
}

export function DocumentCard({ doc, viewer, onOpen }: DocumentCardProps) {
  const [confirmSoftDelete, setConfirmSoftDelete] = useState(false)
  const [confirmHardDelete, setConfirmHardDelete] = useState(false)

  const downloadQuery = useDocumentDownloadUrl(doc.id, { enabled: false })
  const softDelete = useDeleteDocument()
  const restore = useRestoreDocument()
  const hardDelete = useHardDeleteDocument()

  const isDeleted = doc.deletedAt !== null
  const isReceipt = doc.category === 'RECEIPT'
  const isInvoice = doc.category === 'INVOICE'
  const isImage = doc.mimeType.startsWith('image/')
  const isPdf = doc.mimeType === 'application/pdf'

  const isOwner = viewer.id === doc.ownerId
  const isAdmin = viewer.role === 'ADMIN'

  // Standalone soft-delete is forbidden for RECEIPTs (cascade from the
  // parent transaction) AND INVOICEs (generated by InvoicesService, lifecycle
  // owned by the linked transaction).
  const canSoftDelete = !isDeleted && !isReceipt && !isInvoice && (isOwner || isAdmin)
  const canRestore = isDeleted && isAdmin
  const canHardDelete = isDeleted && isAdmin

  // Uploader display name is embedded in the API response (LEFT JOIN
  // on `users`). When the uploader was hard-deleted the field is null
  // and we fall back to a short id so the card still renders.
  const uploaderLabel = doc.uploadedByDisplayName ?? shortId(doc.uploadedBy)

  // Variant 3 hybrid: prefer the original name (cyrillic preserved); fall
  // back to the sanitized `name` for legacy rows that pre-date migration 0011.
  const displayName = doc.originalName ?? doc.name

  // INVOICE-specific: the document filename embeds the first 8 chars of the
  // parent transaction id. We surface them as a deep link into the Invoices
  // page so users can jump to the matching record.
  const invoiceShortId = isInvoice ? extractInvoiceShortId(displayName) : null

  const relativeDate = useMemo(() => {
    try {
      return formatDistanceToNow(new Date(doc.createdAt), {
        addSuffix: true,
        locale: ru,
      })
    } catch {
      return doc.createdAt
    }
  }, [doc.createdAt])

  async function handleDownload() {
    // Refetch on demand — query has 4h staleTime so cached result will hit
    // immediately for subsequent clicks.
    const result = await downloadQuery.refetch()
    const url = result.data?.url
    if (!url) return
    window.open(url, '_blank', 'noopener,noreferrer')
  }

  return (
    <div
      data-testid="document-card"
      data-doc-id={doc.id}
      className={cn(
        'flex flex-col rounded-xl border border-border bg-card shadow-sm transition hover:shadow-md',
        isDeleted && 'opacity-50',
      )}
    >
      <button
        type="button"
        onClick={() => onOpen?.(doc)}
        className="group relative aspect-[4/3] w-full overflow-hidden rounded-t-xl bg-muted text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-primary"
        aria-label={`Открыть документ «${displayName}»`}
        data-testid="document-card-open"
      >
        {/* Fallback icon — always rendered behind; hidden when thumbnail
            covers the area (DocumentImage renders as block over it). */}
        <div className="absolute inset-0 flex h-full w-full flex-col items-center justify-center gap-2 text-muted-foreground transition group-hover:text-foreground">
          <FileText className="h-12 w-12" />
          {isPdf ? (
            <Badge variant="secondary" className="bg-red-500/15 text-red-600">
              PDF
            </Badge>
          ) : null}
        </div>
        {isImage ? (
          <DocumentImage
            docId={doc.id}
            alt={displayName}
            variant="thumbnail"
            fallbackToParent
            className="absolute inset-0 h-full w-full"
          />
        ) : null}

        {isDeleted ? (
          <Badge
            variant="secondary"
            className="absolute right-2 top-2 bg-muted-foreground/15 text-foreground"
          >
            Удалён
          </Badge>
        ) : null}
      </button>

      <div className="flex flex-1 flex-col gap-2 p-4">
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger asChild>
              <button
                type="button"
                onClick={() => onOpen?.(doc)}
                className="line-clamp-1 text-left text-sm font-semibold hover:underline focus:outline-none focus-visible:underline"
                title={displayName}
                data-testid="document-card-title"
              >
                {displayName}
              </button>
            </TooltipTrigger>
            <TooltipContent>{displayName}</TooltipContent>
          </Tooltip>
        </TooltipProvider>

        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <span>{formatBytes(doc.sizeBytes)}</span>
          <span aria-hidden="true">·</span>
          <span title={doc.createdAt}>{relativeDate}</span>
        </div>

        <div className="flex items-center gap-1 text-xs text-muted-foreground">
          <UserCircle2 className="h-3.5 w-3.5" />
          <Link
            to="/crm/profile/$userId"
            params={{ userId: doc.uploadedBy }}
            className="line-clamp-1 hover:text-foreground hover:underline focus:outline-none focus-visible:text-foreground focus-visible:underline"
            data-testid="document-card-uploader-link"
          >
            {uploaderLabel}
          </Link>
        </div>

        {isReceipt && doc.projectId ? (
          <Link
            to="/crm/finance"
            className="inline-flex items-center gap-1 text-xs text-primary hover:underline"
          >
            <ReceiptIcon className="h-3.5 w-3.5" />К транзакции #{shortId(doc.projectId)}
          </Link>
        ) : null}

        {isInvoice && invoiceShortId ? (
          // The card itself opens InvoiceDetailDialog (parent's onOpen
          // handler routes INVOICE category to the invoice-specific
          // dialog). We surface the 8-char tx prefix as a passive label so
          // users can correlate the row with the matching transaction.
          <span
            className="inline-flex items-center gap-1 text-xs text-muted-foreground"
            data-testid="document-card-invoice-label"
          >
            <FileSignature className="h-3.5 w-3.5" />
            Инвойс #{invoiceShortId}
          </span>
        ) : null}

        {/* PR-2: unified status badge (supersedes invoicePendingSignature). */}
        {doc.statusBadge ? <DocumentStatusBadge badge={doc.statusBadge} className="w-fit" /> : null}
        {/* Back-compat: render amber badge for pre-PR-2 rows that still carry
            invoicePendingSignature but no statusBadge. */}
        {!doc.statusBadge && doc.invoicePendingSignature ? (
          <Badge
            className="w-fit border-amber-500/30 bg-amber-500/20 text-amber-300 hover:bg-amber-500/30"
            data-testid="document-card-pending-signature"
          >
            Требует подписи
          </Badge>
        ) : null}

        <div className="mt-auto flex flex-wrap gap-1 pt-3">
          <Button
            size="sm"
            variant="outline"
            onClick={handleDownload}
            disabled={downloadQuery.isFetching}
            data-testid="document-download"
          >
            <Download className="mr-1 h-4 w-4" />
            Скачать
          </Button>

          {canSoftDelete ? (
            <Button
              size="sm"
              variant="ghost"
              className="text-muted-foreground hover:text-destructive"
              onClick={() => setConfirmSoftDelete(true)}
              data-testid="document-delete"
              aria-label="Удалить"
            >
              <Trash className="h-4 w-4" />
            </Button>
          ) : null}

          {isReceipt && !isDeleted ? (
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <span>
                    <Button
                      size="sm"
                      variant="ghost"
                      disabled
                      className="text-muted-foreground"
                      aria-label="Удалить (недоступно для чеков)"
                    >
                      <Trash className="h-4 w-4" />
                    </Button>
                  </span>
                </TooltipTrigger>
                <TooltipContent>{RECEIPT_DELETE_TOOLTIP}</TooltipContent>
              </Tooltip>
            </TooltipProvider>
          ) : null}

          {isInvoice && !isDeleted ? (
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <span>
                    <Button
                      size="sm"
                      variant="ghost"
                      disabled
                      className="text-muted-foreground"
                      aria-label="Удалить (недоступно для инвойсов)"
                      data-testid="document-delete-invoice-disabled"
                    >
                      <Trash className="h-4 w-4" />
                    </Button>
                  </span>
                </TooltipTrigger>
                <TooltipContent>{INVOICE_DELETE_TOOLTIP}</TooltipContent>
              </Tooltip>
            </TooltipProvider>
          ) : null}

          {canRestore ? (
            <Button
              size="sm"
              variant="outline"
              onClick={() => restore.mutate(doc.id)}
              disabled={restore.isPending}
              data-testid="document-restore"
            >
              <RotateCcw className="mr-1 h-4 w-4" />
              Восстановить
            </Button>
          ) : null}

          {canHardDelete ? (
            <Button
              size="sm"
              variant="destructive"
              onClick={() => setConfirmHardDelete(true)}
              disabled={hardDelete.isPending}
              data-testid="document-hard-delete"
            >
              <Trash2 className="mr-1 h-4 w-4" />
              Удалить навсегда
            </Button>
          ) : null}
        </div>
      </div>

      {/* Soft delete confirm */}
      <AlertDialog open={confirmSoftDelete} onOpenChange={setConfirmSoftDelete}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Переместить в корзину?</AlertDialogTitle>
            <AlertDialogDescription>
              Документ «{displayName}» можно восстановить позже из режима «Архив».
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Отмена</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                softDelete.mutate(doc.id)
                setConfirmSoftDelete(false)
              }}
            >
              Удалить
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Hard delete confirm — ADMIN only */}
      <AlertDialog open={confirmHardDelete} onOpenChange={setConfirmHardDelete}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Удалить навсегда?</AlertDialogTitle>
            <AlertDialogDescription>
              Файл будет удалён навсегда из S3 и базы. Действие необратимо. Продолжить?
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Отмена</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              onClick={() => {
                hardDelete.mutate(doc.id)
                setConfirmHardDelete(false)
              }}
            >
              Удалить навсегда
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}
