import type { MessageDescriptor } from '@lingui/core'

/**
 * task-i18n-stage4-task1 (Track A). Error codes for `auth`/`users`/`projects`
 * throw-sites that used to carry a literal Russian or English message —
 * `apiError()` call sites now route through these codes instead. Source
 * locale is Ukrainian (spec decision: Russian leaves the product; see
 * `CONTEXT.md`). None of these codes takes a `params` — every original
 * message was either static or the interpolated value was dropped in favor
 * of a generic phrasing (see `CANNOT_REMOVE_LAST_ROLE_MEMBER`'s PR-body note
 * for why the one `${role}` interpolation was not carried through as an ICU
 * `select` — it would have collided with `api-errors.spec.ts`'s naive
 * `{token}` regex, which does not parse nested ICU syntax).
 */
export const AUTH_USERS_PROJECTS_ERROR_CODES = [
  'ACCOUNT_DISABLED',
  'ACTIVE_MEMBER_NOT_FOUND',
  'ADMIN_CANNOT_CHANGE_OWN_ROLE',
  'ADMIN_CREATION_FORBIDDEN',
  'ADMIN_ROLE_ASSIGNMENT_FORBIDDEN',
  'ALREADY_ACTIVE_PROJECT_MEMBER',
  'ALREADY_HAS_ACTIVE_TEAM',
  'ARCHIVED_USER_CANNOT_JOIN_PROJECT',
  'AVATAR_DOCUMENT_DELETED',
  'AVATAR_DOCUMENT_NOT_FOUND',
  'AVATAR_DOCUMENT_WRONG_CATEGORY',
  'AVATAR_DOCUMENT_WRONG_OWNER',
  'CANNOT_ARCHIVE_ANOTHER_ADMIN',
  'CANNOT_ARCHIVE_YOURSELF',
  'CANNOT_EDIT_ANOTHER_ADMIN',
  'CANNOT_REMOVE_LAST_ROLE_MEMBER',
  'DROP_ARCHIVED',
  'DROP_ARCHIVE_ADMIN_ONLY',
  'DROP_CREATE_ADMIN_ONLY',
  'DROP_CREATE_VIA_DEDICATED_ENDPOINT',
  'DROP_NOT_FOUND',
  'DROP_PROJECT_ACCESS_DENIED',
  'DROP_ROLE_CHANGE_VIA_DEDICATED_ENDPOINT',
  'DROP_SHARE_OVERRIDE_FORBIDDEN',
  'DROP_TEAM_ID_REQUIRED',
  'EMAIL_ALREADY_IN_USE',
  'EMAIL_NOT_AUTHORIZED',
  'EMAIL_TAKEN_BY_ANOTHER_USER',
  'GOOGLE_ACCOUNT_MISMATCH',
  'GOOGLE_CREDENTIAL_INVALID',
  'HR_JOIN_OWN_DROP_TEAM_ONLY',
  'HR_REQUIRED_MINIMUM_ONE',
  'HR_SENIOR_ONLY_CREATION',
  'IMPERSONATION_ALREADY_ACTIVE',
  'IMPERSONATION_NOT_ACTIVE',
  'IMPERSONATION_ORIGIN_UNAVAILABLE',
  'IMPERSONATION_SELF_FORBIDDEN',
  'IMPERSONATION_TARGET_ADMIN_FORBIDDEN',
  'INVITE_ALREADY_USED',
  'INVITE_EXPIRED',
  'INVITE_GOOGLE_ACCOUNT_MISMATCH',
  'INVITE_INVALID',
  'JOIN_DROP_TEAM_SENIOR_ONLY',
  'JUNIOR_ALREADY_ON_ANOTHER_PROJECT',
  'LOGO_DOCUMENT_DELETED',
  'LOGO_DOCUMENT_NOT_FOUND',
  'LOGO_DOCUMENT_WRONG_CATEGORY',
  'LOGO_DOCUMENT_WRONG_PROJECT',
  'METHOD_DROP_ONLY',
  'NO_HR_CONTACT_ACCESS',
  'PAYMENT_TYPE_CHANGE_FORBIDDEN',
  'PERSONAL_EMAIL_ALREADY_VERIFIED',
  'PERSONAL_EMAIL_MUST_DIFFER_FROM_WORK',
  'PERSONAL_EMAIL_NOT_SET',
  'PROJECT_ALREADY_ARCHIVED',
  'PROJECT_HAS_ACTIVE_JUNIOR',
  'PROJECT_MEMBER_ROLE_RESTRICTED',
  'PROJECT_NOT_ACTIVE',
  'PROJECT_NOT_ARCHIVED',
  'PROJECT_NOT_FOUND',
  'PROJECT_NOT_IN_YOUR_TEAMS',
  'REJOIN_TEAM_MUST_BE_FORMER_MEMBER',
  'REJOIN_TEAM_SENIOR_ONLY',
  'SENIOR_ADMIN_USDT_ONLY',
  'SENIOR_NOT_FOUND',
  'SENIOR_SHARE_OVERRIDE_FORBIDDEN',
  'SHARE_APPROVE_IMPERSONATION_FORBIDDEN',
  'SHARE_CANCEL_ADMIN_ACCOUNTANT_ONLY',
  'SHARE_CANCEL_ADMIN_ONLY',
  'SHARE_CHANGE_REQUESTER_REQUIRED',
  'SHARE_REJECT_IMPERSONATION_FORBIDDEN',
  'TELEGRAM_CHANNEL_SENIOR_ONLY',
  'USER_ALREADY_ARCHIVED',
  'USER_EMAIL_EXISTS',
  'USER_NOT_ARCHIVED',
  'USER_NOT_DROP',
  'USER_NOT_FOUND',
  'USER_NOT_SENIOR_OR_ADMIN',
  'WORK_EMAIL_MUST_DIFFER_FROM_PERSONAL',
] as const
export type AuthUsersProjectsErrorCode = (typeof AUTH_USERS_PROJECTS_ERROR_CODES)[number]

export const AUTH_USERS_PROJECTS_ERROR_PARAMS = {
  ACCOUNT_DISABLED: [],
  ACTIVE_MEMBER_NOT_FOUND: [],
  ADMIN_CANNOT_CHANGE_OWN_ROLE: [],
  ADMIN_CREATION_FORBIDDEN: [],
  ADMIN_ROLE_ASSIGNMENT_FORBIDDEN: [],
  ALREADY_ACTIVE_PROJECT_MEMBER: [],
  ALREADY_HAS_ACTIVE_TEAM: [],
  ARCHIVED_USER_CANNOT_JOIN_PROJECT: [],
  AVATAR_DOCUMENT_DELETED: [],
  AVATAR_DOCUMENT_NOT_FOUND: [],
  AVATAR_DOCUMENT_WRONG_CATEGORY: [],
  AVATAR_DOCUMENT_WRONG_OWNER: [],
  CANNOT_ARCHIVE_ANOTHER_ADMIN: [],
  CANNOT_ARCHIVE_YOURSELF: [],
  CANNOT_EDIT_ANOTHER_ADMIN: [],
  CANNOT_REMOVE_LAST_ROLE_MEMBER: [],
  DROP_ARCHIVED: [],
  DROP_ARCHIVE_ADMIN_ONLY: [],
  DROP_CREATE_ADMIN_ONLY: [],
  DROP_CREATE_VIA_DEDICATED_ENDPOINT: [],
  DROP_NOT_FOUND: [],
  DROP_PROJECT_ACCESS_DENIED: [],
  DROP_ROLE_CHANGE_VIA_DEDICATED_ENDPOINT: [],
  DROP_SHARE_OVERRIDE_FORBIDDEN: [],
  DROP_TEAM_ID_REQUIRED: [],
  EMAIL_ALREADY_IN_USE: [],
  EMAIL_NOT_AUTHORIZED: [],
  EMAIL_TAKEN_BY_ANOTHER_USER: [],
  GOOGLE_ACCOUNT_MISMATCH: [],
  GOOGLE_CREDENTIAL_INVALID: [],
  HR_JOIN_OWN_DROP_TEAM_ONLY: [],
  HR_REQUIRED_MINIMUM_ONE: [],
  HR_SENIOR_ONLY_CREATION: [],
  IMPERSONATION_ALREADY_ACTIVE: [],
  IMPERSONATION_NOT_ACTIVE: [],
  IMPERSONATION_ORIGIN_UNAVAILABLE: [],
  IMPERSONATION_SELF_FORBIDDEN: [],
  IMPERSONATION_TARGET_ADMIN_FORBIDDEN: [],
  INVITE_ALREADY_USED: [],
  INVITE_EXPIRED: [],
  INVITE_GOOGLE_ACCOUNT_MISMATCH: [],
  INVITE_INVALID: [],
  JOIN_DROP_TEAM_SENIOR_ONLY: [],
  JUNIOR_ALREADY_ON_ANOTHER_PROJECT: [],
  LOGO_DOCUMENT_DELETED: [],
  LOGO_DOCUMENT_NOT_FOUND: [],
  LOGO_DOCUMENT_WRONG_CATEGORY: [],
  LOGO_DOCUMENT_WRONG_PROJECT: [],
  METHOD_DROP_ONLY: [],
  NO_HR_CONTACT_ACCESS: [],
  PAYMENT_TYPE_CHANGE_FORBIDDEN: [],
  PERSONAL_EMAIL_ALREADY_VERIFIED: [],
  PERSONAL_EMAIL_MUST_DIFFER_FROM_WORK: [],
  PERSONAL_EMAIL_NOT_SET: [],
  PROJECT_ALREADY_ARCHIVED: [],
  PROJECT_HAS_ACTIVE_JUNIOR: [],
  PROJECT_MEMBER_ROLE_RESTRICTED: [],
  PROJECT_NOT_ACTIVE: [],
  PROJECT_NOT_ARCHIVED: [],
  PROJECT_NOT_FOUND: [],
  PROJECT_NOT_IN_YOUR_TEAMS: [],
  REJOIN_TEAM_MUST_BE_FORMER_MEMBER: [],
  REJOIN_TEAM_SENIOR_ONLY: [],
  SENIOR_ADMIN_USDT_ONLY: [],
  SENIOR_NOT_FOUND: [],
  SENIOR_SHARE_OVERRIDE_FORBIDDEN: [],
  SHARE_APPROVE_IMPERSONATION_FORBIDDEN: [],
  SHARE_CANCEL_ADMIN_ACCOUNTANT_ONLY: [],
  SHARE_CANCEL_ADMIN_ONLY: [],
  SHARE_CHANGE_REQUESTER_REQUIRED: [],
  SHARE_REJECT_IMPERSONATION_FORBIDDEN: [],
  TELEGRAM_CHANNEL_SENIOR_ONLY: [],
  USER_ALREADY_ARCHIVED: [],
  USER_EMAIL_EXISTS: [],
  USER_NOT_ARCHIVED: [],
  USER_NOT_DROP: [],
  USER_NOT_FOUND: [],
  USER_NOT_SENIOR_OR_ADMIN: [],
  WORK_EMAIL_MUST_DIFFER_FROM_PERSONAL: [],
} as const satisfies Record<AuthUsersProjectsErrorCode, readonly string[]>

export const AUTH_USERS_PROJECTS_ERROR_MESSAGES: Record<
  AuthUsersProjectsErrorCode,
  MessageDescriptor
> = {
  ACCOUNT_DISABLED: /* i18n */ {
    id: 'api-error.ACCOUNT_DISABLED',
    message: 'Ваш обліковий запис вимкнено. Зверніться до адміністратора',
  },
  ACTIVE_MEMBER_NOT_FOUND: /* i18n */ {
    id: 'api-error.ACTIVE_MEMBER_NOT_FOUND',
    message: 'Активного учасника в проєкті не знайдено',
  },
  ADMIN_CANNOT_CHANGE_OWN_ROLE: /* i18n */ {
    id: 'api-error.ADMIN_CANNOT_CHANGE_OWN_ROLE',
    message: 'Адміністратор не може змінити власну роль',
  },
  ADMIN_CREATION_FORBIDDEN: /* i18n */ {
    id: 'api-error.ADMIN_CREATION_FORBIDDEN',
    message: 'Створити адміністратора не можна — пул фіксований',
  },
  ADMIN_ROLE_ASSIGNMENT_FORBIDDEN: /* i18n */ {
    id: 'api-error.ADMIN_ROLE_ASSIGNMENT_FORBIDDEN',
    message: 'Призначити роль адміністратора не можна — пул фіксований',
  },
  ALREADY_ACTIVE_PROJECT_MEMBER: /* i18n */ {
    id: 'api-error.ALREADY_ACTIVE_PROJECT_MEMBER',
    message: 'Користувач уже є активним учасником цього проєкту',
  },
  ALREADY_HAS_ACTIVE_TEAM: /* i18n */ {
    id: 'api-error.ALREADY_HAS_ACTIVE_TEAM',
    message: 'У вас уже є активна команда',
  },
  ARCHIVED_USER_CANNOT_JOIN_PROJECT: /* i18n */ {
    id: 'api-error.ARCHIVED_USER_CANNOT_JOIN_PROJECT',
    message: 'Користувача заархівовано — додати до проєкту не можна',
  },
  AVATAR_DOCUMENT_DELETED: /* i18n */ {
    id: 'api-error.AVATAR_DOCUMENT_DELETED',
    message: 'Документ аватара видалено',
  },
  AVATAR_DOCUMENT_NOT_FOUND: /* i18n */ {
    id: 'api-error.AVATAR_DOCUMENT_NOT_FOUND',
    message: 'Документ аватара не знайдено',
  },
  AVATAR_DOCUMENT_WRONG_CATEGORY: /* i18n */ {
    id: 'api-error.AVATAR_DOCUMENT_WRONG_CATEGORY',
    message: 'Цей документ не аватар',
  },
  AVATAR_DOCUMENT_WRONG_OWNER: /* i18n */ {
    id: 'api-error.AVATAR_DOCUMENT_WRONG_OWNER',
    message: 'Цей документ належить іншому користувачу',
  },
  CANNOT_ARCHIVE_ANOTHER_ADMIN: /* i18n */ {
    id: 'api-error.CANNOT_ARCHIVE_ANOTHER_ADMIN',
    message: 'Не можна заархівувати іншого адміністратора',
  },
  CANNOT_ARCHIVE_YOURSELF: /* i18n */ {
    id: 'api-error.CANNOT_ARCHIVE_YOURSELF',
    message: 'Не можна заархівувати самого себе',
  },
  CANNOT_EDIT_ANOTHER_ADMIN: /* i18n */ {
    id: 'api-error.CANNOT_EDIT_ANOTHER_ADMIN',
    message: 'Не можна редагувати обліковий запис іншого адміністратора',
  },
  CANNOT_REMOVE_LAST_ROLE_MEMBER: /* i18n */ {
    id: 'api-error.CANNOT_REMOVE_LAST_ROLE_MEMBER',
    message: 'У проєкті має залишитися хоча б один учасник цієї ролі',
  },
  DROP_ARCHIVED: /* i18n */ {
    id: 'api-error.DROP_ARCHIVED',
    message: 'Дропа вже заархівовано',
  },
  DROP_ARCHIVE_ADMIN_ONLY: /* i18n */ {
    id: 'api-error.DROP_ARCHIVE_ADMIN_ONLY',
    message: 'Архівація дропа доступна лише адміністратору',
  },
  DROP_CREATE_ADMIN_ONLY: /* i18n */ {
    id: 'api-error.DROP_CREATE_ADMIN_ONLY',
    message: 'Створення дропа доступне лише адміністратору',
  },
  DROP_CREATE_VIA_DEDICATED_ENDPOINT: /* i18n */ {
    id: 'api-error.DROP_CREATE_VIA_DEDICATED_ENDPOINT',
    message: 'Створити дропа цим способом не можна',
  },
  DROP_NOT_FOUND: /* i18n */ {
    id: 'api-error.DROP_NOT_FOUND',
    message: 'Дропа не знайдено',
  },
  DROP_PROJECT_ACCESS_DENIED: /* i18n */ {
    id: 'api-error.DROP_PROJECT_ACCESS_DENIED',
    message: 'Проєкти дропа доступні лише дропам',
  },
  DROP_ROLE_CHANGE_VIA_DEDICATED_ENDPOINT: /* i18n */ {
    id: 'api-error.DROP_ROLE_CHANGE_VIA_DEDICATED_ENDPOINT',
    message: 'Змінити роль на «дроп» цим способом не можна',
  },
  DROP_SHARE_OVERRIDE_FORBIDDEN: /* i18n */ {
    id: 'api-error.DROP_SHARE_OVERRIDE_FORBIDDEN',
    message: 'Індивідуальну частку дропа за проєктом змінюють лише адміністратор і бухгалтер',
  },
  DROP_TEAM_ID_REQUIRED: /* i18n */ {
    id: 'api-error.DROP_TEAM_ID_REQUIRED',
    message: 'Виберіть команду дропа, до якої приєднати сеньйора',
  },
  EMAIL_ALREADY_IN_USE: /* i18n */ {
    id: 'api-error.EMAIL_ALREADY_IN_USE',
    message: 'Ця електронна адреса вже зайнята. Введіть іншу',
  },
  EMAIL_NOT_AUTHORIZED: /* i18n */ {
    id: 'api-error.EMAIL_NOT_AUTHORIZED',
    message: 'Ця електронна адреса не має доступу',
  },
  EMAIL_TAKEN_BY_ANOTHER_USER: /* i18n */ {
    id: 'api-error.EMAIL_TAKEN_BY_ANOTHER_USER',
    message: 'Ця електронна адреса вже зайнята. Введіть іншу',
  },
  GOOGLE_ACCOUNT_MISMATCH: /* i18n */ {
    id: 'api-error.GOOGLE_ACCOUNT_MISMATCH',
    message: 'Ця адреса вже прив’язана до іншого облікового запису Google',
  },
  GOOGLE_CREDENTIAL_INVALID: /* i18n */ {
    id: 'api-error.GOOGLE_CREDENTIAL_INVALID',
    message: 'Не вдалося підтвердити вхід через Google. Спробуйте ще раз',
  },
  HR_JOIN_OWN_DROP_TEAM_ONLY: /* i18n */ {
    id: 'api-error.HR_JOIN_OWN_DROP_TEAM_ONLY',
    message: 'HR може приєднати сеньйора лише до своєї команди дропа',
  },
  HR_REQUIRED_MINIMUM_ONE: /* i18n */ {
    id: 'api-error.HR_REQUIRED_MINIMUM_ONE',
    message: 'Потрібен щонайменше один HR',
  },
  HR_SENIOR_ONLY_CREATION: /* i18n */ {
    id: 'api-error.HR_SENIOR_ONLY_CREATION',
    message: 'HR може створювати лише сеньйорів',
  },
  IMPERSONATION_ALREADY_ACTIVE: /* i18n */ {
    id: 'api-error.IMPERSONATION_ALREADY_ACTIVE',
    message: 'Ви вже увійшли як інший співробітник — спершу поверніться до свого облікового запису',
  },
  IMPERSONATION_NOT_ACTIVE: /* i18n */ {
    id: 'api-error.IMPERSONATION_NOT_ACTIVE',
    message: 'Ви не входили як інший співробітник',
  },
  IMPERSONATION_ORIGIN_UNAVAILABLE: /* i18n */ {
    id: 'api-error.IMPERSONATION_ORIGIN_UNAVAILABLE',
    message: 'Не вдалося повернутися до вашого облікового запису. Увійдіть заново',
  },
  IMPERSONATION_SELF_FORBIDDEN: /* i18n */ {
    id: 'api-error.IMPERSONATION_SELF_FORBIDDEN',
    message: 'Увійти як самого себе не можна',
  },
  IMPERSONATION_TARGET_ADMIN_FORBIDDEN: /* i18n */ {
    id: 'api-error.IMPERSONATION_TARGET_ADMIN_FORBIDDEN',
    message: 'Увійти як інший адміністратор не можна',
  },
  INVITE_ALREADY_USED: /* i18n */ {
    id: 'api-error.INVITE_ALREADY_USED',
    message: 'Запрошення вже використано',
  },
  INVITE_EXPIRED: /* i18n */ {
    id: 'api-error.INVITE_EXPIRED',
    message: 'Термін дії запрошення закінчився',
  },
  INVITE_GOOGLE_ACCOUNT_MISMATCH: /* i18n */ {
    id: 'api-error.INVITE_GOOGLE_ACCOUNT_MISMATCH',
    message: 'Обліковий запис Google не збігається з адресою, на яку надіслано запрошення',
  },
  INVITE_INVALID: /* i18n */ {
    id: 'api-error.INVITE_INVALID',
    message: 'Запрошення недійсне',
  },
  JOIN_DROP_TEAM_SENIOR_ONLY: /* i18n */ {
    id: 'api-error.JOIN_DROP_TEAM_SENIOR_ONLY',
    message: 'Приєднати до команди дропа можна лише сеньйора',
  },
  JUNIOR_ALREADY_ON_ANOTHER_PROJECT: /* i18n */ {
    id: 'api-error.JUNIOR_ALREADY_ON_ANOTHER_PROJECT',
    message: 'Джуніор уже є активним учасником іншого проєкту',
  },
  LOGO_DOCUMENT_DELETED: /* i18n */ {
    id: 'api-error.LOGO_DOCUMENT_DELETED',
    message: 'Документ логотипа видалено',
  },
  LOGO_DOCUMENT_NOT_FOUND: /* i18n */ {
    id: 'api-error.LOGO_DOCUMENT_NOT_FOUND',
    message: 'Документ логотипа не знайдено',
  },
  LOGO_DOCUMENT_WRONG_CATEGORY: /* i18n */ {
    id: 'api-error.LOGO_DOCUMENT_WRONG_CATEGORY',
    message: 'Цей документ не логотип',
  },
  LOGO_DOCUMENT_WRONG_PROJECT: /* i18n */ {
    id: 'api-error.LOGO_DOCUMENT_WRONG_PROJECT',
    message: 'Цей документ належить іншому проєкту',
  },
  METHOD_DROP_ONLY: /* i18n */ {
    id: 'api-error.METHOD_DROP_ONLY',
    message: 'Ця дія доступна лише для дропів',
  },
  NO_HR_CONTACT_ACCESS: /* i18n */ {
    id: 'api-error.NO_HR_CONTACT_ACCESS',
    message: 'Немає доступу до контакту HR',
  },
  PAYMENT_TYPE_CHANGE_FORBIDDEN: /* i18n */ {
    id: 'api-error.PAYMENT_TYPE_CHANGE_FORBIDDEN',
    message: 'Тип оплати проєкту змінюють лише адміністратор і бухгалтер',
  },
  PERSONAL_EMAIL_ALREADY_VERIFIED: /* i18n */ {
    id: 'api-error.PERSONAL_EMAIL_ALREADY_VERIFIED',
    message: 'Особисту адресу вже підтверджено — повторне запрошення не потрібне',
  },
  PERSONAL_EMAIL_MUST_DIFFER_FROM_WORK: /* i18n */ {
    id: 'api-error.PERSONAL_EMAIL_MUST_DIFFER_FROM_WORK',
    message: 'Особиста адреса має відрізнятися від робочої',
  },
  PERSONAL_EMAIL_NOT_SET: /* i18n */ {
    id: 'api-error.PERSONAL_EMAIL_NOT_SET',
    message: 'У користувача не вказано особисту адресу',
  },
  PROJECT_ALREADY_ARCHIVED: /* i18n */ {
    id: 'api-error.PROJECT_ALREADY_ARCHIVED',
    message: 'Проєкт уже заархівовано',
  },
  PROJECT_HAS_ACTIVE_JUNIOR: /* i18n */ {
    id: 'api-error.PROJECT_HAS_ACTIVE_JUNIOR',
    message: 'У проєкту вже є активний джуніор',
  },
  PROJECT_MEMBER_ROLE_RESTRICTED: /* i18n */ {
    id: 'api-error.PROJECT_MEMBER_ROLE_RESTRICTED',
    message: 'До складу проєкту можна додати лише джуніора, HR або бухгалтера',
  },
  PROJECT_NOT_ACTIVE: /* i18n */ {
    id: 'api-error.PROJECT_NOT_ACTIVE',
    message: 'Проєкт ще не активний — операції з ним недоступні',
  },
  PROJECT_NOT_ARCHIVED: /* i18n */ {
    id: 'api-error.PROJECT_NOT_ARCHIVED',
    message: 'Проєкт не заархівовано',
  },
  PROJECT_NOT_FOUND: /* i18n */ {
    id: 'api-error.PROJECT_NOT_FOUND',
    message: 'Проєкт не знайдено',
  },
  PROJECT_NOT_IN_YOUR_TEAMS: /* i18n */ {
    id: 'api-error.PROJECT_NOT_IN_YOUR_TEAMS',
    message: 'Немає доступу: проєкт не належить вашим командам',
  },
  REJOIN_TEAM_MUST_BE_FORMER_MEMBER: /* i18n */ {
    id: 'api-error.REJOIN_TEAM_MUST_BE_FORMER_MEMBER',
    message: 'Самостійно приєднатися можна лише до команди, в якій ви вже були',
  },
  REJOIN_TEAM_SENIOR_ONLY: /* i18n */ {
    id: 'api-error.REJOIN_TEAM_SENIOR_ONLY',
    message: 'Повернутися до команди може лише сеньйор',
  },
  SENIOR_ADMIN_USDT_ONLY: /* i18n */ {
    id: 'api-error.SENIOR_ADMIN_USDT_ONLY',
    message: 'Для сеньйора й адміністратора доступний лише один спосіб виплати — USDT ERC-20',
  },
  SENIOR_NOT_FOUND: /* i18n */ {
    id: 'api-error.SENIOR_NOT_FOUND',
    message: 'Сеньйора не знайдено',
  },
  SENIOR_SHARE_OVERRIDE_FORBIDDEN: /* i18n */ {
    id: 'api-error.SENIOR_SHARE_OVERRIDE_FORBIDDEN',
    message: 'Індивідуальну частку сеньйора за проєктом змінюють лише адміністратор і бухгалтер',
  },
  SHARE_APPROVE_IMPERSONATION_FORBIDDEN: /* i18n */ {
    id: 'api-error.SHARE_APPROVE_IMPERSONATION_FORBIDDEN',
    message: 'Ви увійшли як інший співробітник — підтвердити його частку може лише він сам',
  },
  SHARE_CANCEL_ADMIN_ACCOUNTANT_ONLY: /* i18n */ {
    id: 'api-error.SHARE_CANCEL_ADMIN_ACCOUNTANT_ONLY',
    message: 'Скасувати пропозицію частки можуть лише адміністратор і бухгалтер',
  },
  SHARE_CANCEL_ADMIN_ONLY: /* i18n */ {
    id: 'api-error.SHARE_CANCEL_ADMIN_ONLY',
    message: 'Скасувати пропозицію частки може лише адміністратор',
  },
  SHARE_CHANGE_REQUESTER_REQUIRED: /* i18n */ {
    id: 'api-error.SHARE_CHANGE_REQUESTER_REQUIRED',
    message: 'Не вдалося змінити частку. Спробуйте ще раз',
  },
  SHARE_REJECT_IMPERSONATION_FORBIDDEN: /* i18n */ {
    id: 'api-error.SHARE_REJECT_IMPERSONATION_FORBIDDEN',
    message: 'Ви увійшли як інший співробітник — відхилити його частку може лише він сам',
  },
  TELEGRAM_CHANNEL_SENIOR_ONLY: /* i18n */ {
    id: 'api-error.TELEGRAM_CHANNEL_SENIOR_ONLY',
    message: 'Telegram-канал можна вказати лише сеньйору',
  },
  USER_ALREADY_ARCHIVED: /* i18n */ {
    id: 'api-error.USER_ALREADY_ARCHIVED',
    message: 'Користувача вже заархівовано',
  },
  USER_EMAIL_EXISTS: /* i18n */ {
    id: 'api-error.USER_EMAIL_EXISTS',
    message: 'Ця електронна адреса вже зайнята. Введіть іншу',
  },
  USER_NOT_ARCHIVED: /* i18n */ {
    id: 'api-error.USER_NOT_ARCHIVED',
    message: 'Користувача не заархівовано',
  },
  USER_NOT_DROP: /* i18n */ {
    id: 'api-error.USER_NOT_DROP',
    message: 'Цей користувач не дроп',
  },
  USER_NOT_FOUND: /* i18n */ {
    id: 'api-error.USER_NOT_FOUND',
    message: 'Користувача не знайдено',
  },
  USER_NOT_SENIOR_OR_ADMIN: /* i18n */ {
    id: 'api-error.USER_NOT_SENIOR_OR_ADMIN',
    message: 'Цей користувач не сеньйор і не адміністратор',
  },
  WORK_EMAIL_MUST_DIFFER_FROM_PERSONAL: /* i18n */ {
    id: 'api-error.WORK_EMAIL_MUST_DIFFER_FROM_PERSONAL',
    message: 'Робоча адреса має відрізнятися від особистої',
  },
}

export const AUTH_USERS_PROJECTS_ERROR_FALLBACK_EN: Record<AuthUsersProjectsErrorCode, string> = {
  ACCOUNT_DISABLED: 'Your account is disabled. Contact an admin',
  ACTIVE_MEMBER_NOT_FOUND: 'Active member not found in the project',
  ADMIN_CANNOT_CHANGE_OWN_ROLE: "An admin can't change their own role",
  ADMIN_CREATION_FORBIDDEN: "You can't create an admin — the pool is fixed",
  ADMIN_ROLE_ASSIGNMENT_FORBIDDEN: "You can't assign the admin role — the pool is fixed",
  ALREADY_ACTIVE_PROJECT_MEMBER: 'The user is already an active member of this project',
  ALREADY_HAS_ACTIVE_TEAM: 'You already have an active team',
  ARCHIVED_USER_CANNOT_JOIN_PROJECT: "The user is archived — they can't be added to the project",
  AVATAR_DOCUMENT_DELETED: 'The avatar document was deleted',
  AVATAR_DOCUMENT_NOT_FOUND: 'The avatar document was not found',
  AVATAR_DOCUMENT_WRONG_CATEGORY: 'This document is not an avatar',
  AVATAR_DOCUMENT_WRONG_OWNER: 'This document belongs to another user',
  CANNOT_ARCHIVE_ANOTHER_ADMIN: "You can't archive another admin",
  CANNOT_ARCHIVE_YOURSELF: "You can't archive yourself",
  CANNOT_EDIT_ANOTHER_ADMIN: "You can't edit another admin's account",
  CANNOT_REMOVE_LAST_ROLE_MEMBER: 'The project must keep at least one member with this role',
  DROP_ARCHIVED: 'The drop is already archived',
  DROP_ARCHIVE_ADMIN_ONLY: 'Only an admin can archive a drop',
  DROP_CREATE_ADMIN_ONLY: 'Only an admin can create a drop',
  DROP_CREATE_VIA_DEDICATED_ENDPOINT: "A drop can't be created this way",
  DROP_NOT_FOUND: 'Drop not found',
  DROP_PROJECT_ACCESS_DENIED: 'Drop projects are only available to drops',
  DROP_ROLE_CHANGE_VIA_DEDICATED_ENDPOINT: "The role can't be changed to drop this way",
  DROP_SHARE_OVERRIDE_FORBIDDEN:
    "Only an admin or an accountant can change the drop's project share",
  DROP_TEAM_ID_REQUIRED: 'Choose the drop team to add the senior to',
  EMAIL_ALREADY_IN_USE: 'This email is already taken. Enter a different one',
  EMAIL_NOT_AUTHORIZED: 'This email is not authorized',
  EMAIL_TAKEN_BY_ANOTHER_USER: 'This email is already taken. Enter a different one',
  GOOGLE_ACCOUNT_MISMATCH: 'This email is already linked to a different Google account',
  GOOGLE_CREDENTIAL_INVALID: "Couldn't verify your Google sign-in. Try again",
  HR_JOIN_OWN_DROP_TEAM_ONLY: 'HR can only add a senior to their own drop team',
  HR_REQUIRED_MINIMUM_ONE: 'At least one HR is required',
  HR_SENIOR_ONLY_CREATION: 'HR can only create seniors',
  IMPERSONATION_ALREADY_ACTIVE:
    "You're already signed in as another employee — return to your own account first",
  IMPERSONATION_NOT_ACTIVE: "You're not signed in as another employee",
  IMPERSONATION_ORIGIN_UNAVAILABLE: "Couldn't return to your own account. Sign in again",
  IMPERSONATION_SELF_FORBIDDEN: "You can't sign in as yourself",
  IMPERSONATION_TARGET_ADMIN_FORBIDDEN: "You can't sign in as another admin",
  INVITE_ALREADY_USED: 'The invite has already been used',
  INVITE_EXPIRED: 'The invite has expired',
  INVITE_GOOGLE_ACCOUNT_MISMATCH:
    "This Google account doesn't match the email the invite was sent to",
  INVITE_INVALID: 'The invite is invalid',
  JOIN_DROP_TEAM_SENIOR_ONLY: 'Only a senior can be added to a drop team',
  JUNIOR_ALREADY_ON_ANOTHER_PROJECT: 'The junior is already an active member of another project',
  LOGO_DOCUMENT_DELETED: 'The logo document was deleted',
  LOGO_DOCUMENT_NOT_FOUND: 'The logo document was not found',
  LOGO_DOCUMENT_WRONG_CATEGORY: 'This document is not a logo',
  LOGO_DOCUMENT_WRONG_PROJECT: 'This document belongs to another project',
  METHOD_DROP_ONLY: 'This action is only available for drops',
  NO_HR_CONTACT_ACCESS: 'No access to the HR contact',
  PAYMENT_TYPE_CHANGE_FORBIDDEN:
    "Only an admin or an accountant can change the project's payment type",
  PERSONAL_EMAIL_ALREADY_VERIFIED:
    "The personal email is already verified — there's no need to send another invite",
  PERSONAL_EMAIL_MUST_DIFFER_FROM_WORK: 'The personal email must be different from the work email',
  PERSONAL_EMAIL_NOT_SET: 'The user has no personal email set',
  PROJECT_ALREADY_ARCHIVED: 'The project is already archived',
  PROJECT_HAS_ACTIVE_JUNIOR: 'The project already has an active junior member',
  PROJECT_MEMBER_ROLE_RESTRICTED:
    'Only a junior, an HR, or an accountant can be added to a project',
  PROJECT_NOT_ACTIVE: 'The project is not active yet — operations with it are unavailable',
  PROJECT_NOT_ARCHIVED: 'The project is not archived',
  PROJECT_NOT_FOUND: 'Project not found',
  PROJECT_NOT_IN_YOUR_TEAMS: "No access: this project isn't in your teams",
  REJOIN_TEAM_MUST_BE_FORMER_MEMBER: 'You can only rejoin a team you were previously a member of',
  REJOIN_TEAM_SENIOR_ONLY: 'Only a senior can rejoin a team',
  SENIOR_ADMIN_USDT_ONLY: 'Seniors and admins can only be paid to USDT ERC-20',
  SENIOR_NOT_FOUND: 'Senior not found',
  SENIOR_SHARE_OVERRIDE_FORBIDDEN:
    "Only an admin or an accountant can change the senior's project share",
  SHARE_APPROVE_IMPERSONATION_FORBIDDEN:
    "You're signed in as another employee — only they can approve their share",
  SHARE_CANCEL_ADMIN_ACCOUNTANT_ONLY: 'Only an admin or an accountant can cancel a share proposal',
  SHARE_CANCEL_ADMIN_ONLY: 'Only an admin can cancel a share proposal',
  SHARE_CHANGE_REQUESTER_REQUIRED: "Couldn't change the share. Try again",
  SHARE_REJECT_IMPERSONATION_FORBIDDEN:
    "You're signed in as another employee — only they can reject their share",
  TELEGRAM_CHANNEL_SENIOR_ONLY: 'A Telegram channel can only be set for a senior',
  USER_ALREADY_ARCHIVED: 'The user is already archived',
  USER_EMAIL_EXISTS: 'This email is already taken. Enter a different one',
  USER_NOT_ARCHIVED: 'The user is not archived',
  USER_NOT_DROP: 'This user is not a drop',
  USER_NOT_FOUND: 'User not found',
  USER_NOT_SENIOR_OR_ADMIN: 'This user is neither a senior nor an admin',
  WORK_EMAIL_MUST_DIFFER_FROM_PERSONAL: 'The work email must be different from the personal email',
}
