import type { MessageDescriptor } from '@lingui/core'

/**
 * task-i18n-stage4-task1 (Track A). Error codes for `auth`/`users`/`projects`
 * throw-sites that used to carry a literal Russian or English message —
 * `apiError()` call sites now route through these codes instead. Source
 * locale is Ukrainian (spec decision: Russian leaves the product; see
 * `CONTEXT.md`). None of these codes takes a `params` — every original
 * message was either static or the interpolated value was dropped in favor
 * of a generic phrasing (see `CANNOT_REMOVE_LAST_ROLE_MEMBER`'s PR-body note
 * for why the one `${role}` interpolation was not carried through as an ICU
 * `select` — it would have collided with `api-errors.spec.ts`'s naive
 * `{token}` regex, which does not parse nested ICU syntax).
 */
export const AUTH_USERS_PROJECTS_ERROR_CODES = [
  'ACCOUNT_DISABLED',
  'ACTIVE_MEMBER_NOT_FOUND',
  'ADMIN_CANNOT_CHANGE_OWN_ROLE',
  'ADMIN_CREATION_FORBIDDEN',
  'ADMIN_ROLE_ASSIGNMENT_FORBIDDEN',
  'ALREADY_ACTIVE_PROJECT_MEMBER',
  'ALREADY_HAS_ACTIVE_TEAM',
  'ARCHIVED_USER_CANNOT_JOIN_PROJECT',
  'AVATAR_DOCUMENT_DELETED',
  'AVATAR_DOCUMENT_NOT_FOUND',
  'AVATAR_DOCUMENT_WRONG_CATEGORY',
  'AVATAR_DOCUMENT_WRONG_OWNER',
  'CANNOT_ARCHIVE_ANOTHER_ADMIN',
  'CANNOT_ARCHIVE_YOURSELF',
  'CANNOT_EDIT_ANOTHER_ADMIN',
  'CANNOT_REMOVE_LAST_ROLE_MEMBER',
  'DROP_ARCHIVED',
  'DROP_ARCHIVE_ADMIN_ONLY',
  'DROP_CREATE_ADMIN_ONLY',
  'DROP_CREATE_VIA_DEDICATED_ENDPOINT',
  'DROP_NOT_FOUND',
  'DROP_PROJECT_ACCESS_DENIED',
  'DROP_ROLE_CHANGE_VIA_DEDICATED_ENDPOINT',
  'DROP_SHARE_OVERRIDE_FORBIDDEN',
  'DROP_TEAM_ID_REQUIRED',
  'EMAIL_ALREADY_IN_USE',
  'EMAIL_NOT_AUTHORIZED',
  'EMAIL_TAKEN_BY_ANOTHER_USER',
  'GOOGLE_ACCOUNT_MISMATCH',
  'GOOGLE_CREDENTIAL_INVALID',
  'HR_JOIN_OWN_DROP_TEAM_ONLY',
  'HR_REQUIRED_MINIMUM_ONE',
  'HR_SENIOR_ONLY_CREATION',
  'IMPERSONATION_ALREADY_ACTIVE',
  'IMPERSONATION_NOT_ACTIVE',
  'IMPERSONATION_ORIGIN_UNAVAILABLE',
  'IMPERSONATION_SELF_FORBIDDEN',
  'IMPERSONATION_TARGET_ADMIN_FORBIDDEN',
  'INVITE_ALREADY_USED',
  'INVITE_EXPIRED',
  'INVITE_GOOGLE_ACCOUNT_MISMATCH',
  'INVITE_INVALID',
  'JOIN_DROP_TEAM_SENIOR_ONLY',
  'JUNIOR_ALREADY_ON_ANOTHER_PROJECT',
  'LOGO_DOCUMENT_DELETED',
  'LOGO_DOCUMENT_NOT_FOUND',
  'LOGO_DOCUMENT_WRONG_CATEGORY',
  'LOGO_DOCUMENT_WRONG_PROJECT',
  'METHOD_DROP_ONLY',
  'NO_HR_CONTACT_ACCESS',
  'PAYMENT_TYPE_CHANGE_FORBIDDEN',
  'PERSONAL_EMAIL_ALREADY_VERIFIED',
  'PERSONAL_EMAIL_MUST_DIFFER_FROM_WORK',
  'PERSONAL_EMAIL_NOT_SET',
  'PROJECT_ALREADY_ARCHIVED',
  'PROJECT_HAS_ACTIVE_JUNIOR',
  'PROJECT_MEMBER_ROLE_RESTRICTED',
  'PROJECT_NOT_ARCHIVED',
  'PROJECT_NOT_FOUND',
  'PROJECT_NOT_IN_YOUR_TEAMS',
  'REJOIN_TEAM_MUST_BE_FORMER_MEMBER',
  'REJOIN_TEAM_SENIOR_ONLY',
  'SENIOR_ADMIN_USDT_ONLY',
  'SENIOR_NOT_FOUND',
  'SENIOR_SHARE_OVERRIDE_FORBIDDEN',
  'SHARE_APPROVE_IMPERSONATION_FORBIDDEN',
  'SHARE_CANCEL_ADMIN_ACCOUNTANT_ONLY',
  'SHARE_CANCEL_ADMIN_ONLY',
  'SHARE_CHANGE_REQUESTER_REQUIRED',
  'SHARE_REJECT_IMPERSONATION_FORBIDDEN',
  'TELEGRAM_CHANNEL_SENIOR_ONLY',
  'USER_ALREADY_ARCHIVED',
  'USER_EMAIL_EXISTS',
  'USER_NOT_ARCHIVED',
  'USER_NOT_DROP',
  'USER_NOT_FOUND',
  'USER_NOT_SENIOR_OR_ADMIN',
  'WORK_EMAIL_MUST_DIFFER_FROM_PERSONAL',
] as const
export type AuthUsersProjectsErrorCode = (typeof AUTH_USERS_PROJECTS_ERROR_CODES)[number]

export const AUTH_USERS_PROJECTS_ERROR_PARAMS = {
  ACCOUNT_DISABLED: [],
  ACTIVE_MEMBER_NOT_FOUND: [],
  ADMIN_CANNOT_CHANGE_OWN_ROLE: [],
  ADMIN_CREATION_FORBIDDEN: [],
  ADMIN_ROLE_ASSIGNMENT_FORBIDDEN: [],
  ALREADY_ACTIVE_PROJECT_MEMBER: [],
  ALREADY_HAS_ACTIVE_TEAM: [],
  ARCHIVED_USER_CANNOT_JOIN_PROJECT: [],
  AVATAR_DOCUMENT_DELETED: [],
  AVATAR_DOCUMENT_NOT_FOUND: [],
  AVATAR_DOCUMENT_WRONG_CATEGORY: [],
  AVATAR_DOCUMENT_WRONG_OWNER: [],
  CANNOT_ARCHIVE_ANOTHER_ADMIN: [],
  CANNOT_ARCHIVE_YOURSELF: [],
  CANNOT_EDIT_ANOTHER_ADMIN: [],
  CANNOT_REMOVE_LAST_ROLE_MEMBER: [],
  DROP_ARCHIVED: [],
  DROP_ARCHIVE_ADMIN_ONLY: [],
  DROP_CREATE_ADMIN_ONLY: [],
  DROP_CREATE_VIA_DEDICATED_ENDPOINT: [],
  DROP_NOT_FOUND: [],
  DROP_PROJECT_ACCESS_DENIED: [],
  DROP_ROLE_CHANGE_VIA_DEDICATED_ENDPOINT: [],
  DROP_SHARE_OVERRIDE_FORBIDDEN: [],
  DROP_TEAM_ID_REQUIRED: [],
  EMAIL_ALREADY_IN_USE: [],
  EMAIL_NOT_AUTHORIZED: [],
  EMAIL_TAKEN_BY_ANOTHER_USER: [],
  GOOGLE_ACCOUNT_MISMATCH: [],
  GOOGLE_CREDENTIAL_INVALID: [],
  HR_JOIN_OWN_DROP_TEAM_ONLY: [],
  HR_REQUIRED_MINIMUM_ONE: [],
  HR_SENIOR_ONLY_CREATION: [],
  IMPERSONATION_ALREADY_ACTIVE: [],
  IMPERSONATION_NOT_ACTIVE: [],
  IMPERSONATION_ORIGIN_UNAVAILABLE: [],
  IMPERSONATION_SELF_FORBIDDEN: [],
  IMPERSONATION_TARGET_ADMIN_FORBIDDEN: [],
  INVITE_ALREADY_USED: [],
  INVITE_EXPIRED: [],
  INVITE_GOOGLE_ACCOUNT_MISMATCH: [],
  INVITE_INVALID: [],
  JOIN_DROP_TEAM_SENIOR_ONLY: [],
  JUNIOR_ALREADY_ON_ANOTHER_PROJECT: [],
  LOGO_DOCUMENT_DELETED: [],
  LOGO_DOCUMENT_NOT_FOUND: [],
  LOGO_DOCUMENT_WRONG_CATEGORY: [],
  LOGO_DOCUMENT_WRONG_PROJECT: [],
  METHOD_DROP_ONLY: [],
  NO_HR_CONTACT_ACCESS: [],
  PAYMENT_TYPE_CHANGE_FORBIDDEN: [],
  PERSONAL_EMAIL_ALREADY_VERIFIED: [],
  PERSONAL_EMAIL_MUST_DIFFER_FROM_WORK: [],
  PERSONAL_EMAIL_NOT_SET: [],
  PROJECT_ALREADY_ARCHIVED: [],
  PROJECT_HAS_ACTIVE_JUNIOR: [],
  PROJECT_MEMBER_ROLE_RESTRICTED: [],
  PROJECT_NOT_ARCHIVED: [],
  PROJECT_NOT_FOUND: [],
  PROJECT_NOT_IN_YOUR_TEAMS: [],
  REJOIN_TEAM_MUST_BE_FORMER_MEMBER: [],
  REJOIN_TEAM_SENIOR_ONLY: [],
  SENIOR_ADMIN_USDT_ONLY: [],
  SENIOR_NOT_FOUND: [],
  SENIOR_SHARE_OVERRIDE_FORBIDDEN: [],
  SHARE_APPROVE_IMPERSONATION_FORBIDDEN: [],
  SHARE_CANCEL_ADMIN_ACCOUNTANT_ONLY: [],
  SHARE_CANCEL_ADMIN_ONLY: [],
  SHARE_CHANGE_REQUESTER_REQUIRED: [],
  SHARE_REJECT_IMPERSONATION_FORBIDDEN: [],
  TELEGRAM_CHANNEL_SENIOR_ONLY: [],
  USER_ALREADY_ARCHIVED: [],
  USER_EMAIL_EXISTS: [],
  USER_NOT_ARCHIVED: [],
  USER_NOT_DROP: [],
  USER_NOT_FOUND: [],
  USER_NOT_SENIOR_OR_ADMIN: [],
  WORK_EMAIL_MUST_DIFFER_FROM_PERSONAL: [],
} as const satisfies Record<AuthUsersProjectsErrorCode, readonly string[]>

export const AUTH_USERS_PROJECTS_ERROR_MESSAGES: Record<
  AuthUsersProjectsErrorCode,
  MessageDescriptor
> = {
  ACCOUNT_DISABLED: /* i18n */ {
    id: 'api-error.ACCOUNT_DISABLED',
    message: 'Обліковий запис вимкнено',
  },
  ACTIVE_MEMBER_NOT_FOUND: /* i18n */ {
    id: 'api-error.ACTIVE_MEMBER_NOT_FOUND',
    message: 'Активного учасника в проєкті не знайдено',
  },
  ADMIN_CANNOT_CHANGE_OWN_ROLE: /* i18n */ {
    id: 'api-error.ADMIN_CANNOT_CHANGE_OWN_ROLE',
    message: 'Адміністратор не може змінити власну роль',
  },
  ADMIN_CREATION_FORBIDDEN: /* i18n */ {
    id: 'api-error.ADMIN_CREATION_FORBIDDEN',
    message: 'Створення ADMIN заборонено — пул фіксований',
  },
  ADMIN_ROLE_ASSIGNMENT_FORBIDDEN: /* i18n */ {
    id: 'api-error.ADMIN_ROLE_ASSIGNMENT_FORBIDDEN',
    message: 'Призначення ролі ADMIN заборонено — пул фіксований',
  },
  ALREADY_ACTIVE_PROJECT_MEMBER: /* i18n */ {
    id: 'api-error.ALREADY_ACTIVE_PROJECT_MEMBER',
    message: 'Користувач уже є активним учасником цього проєкту',
  },
  ALREADY_HAS_ACTIVE_TEAM: /* i18n */ {
    id: 'api-error.ALREADY_HAS_ACTIVE_TEAM',
    message: 'У вас уже є активна команда',
  },
  ARCHIVED_USER_CANNOT_JOIN_PROJECT: /* i18n */ {
    id: 'api-error.ARCHIVED_USER_CANNOT_JOIN_PROJECT',
    message: 'Користувача заархівовано — додати до проєкту не можна',
  },
  AVATAR_DOCUMENT_DELETED: /* i18n */ {
    id: 'api-error.AVATAR_DOCUMENT_DELETED',
    message: 'Аватар: документ видалено',
  },
  AVATAR_DOCUMENT_NOT_FOUND: /* i18n */ {
    id: 'api-error.AVATAR_DOCUMENT_NOT_FOUND',
    message: 'Аватар: документ не знайдено',
  },
  AVATAR_DOCUMENT_WRONG_CATEGORY: /* i18n */ {
    id: 'api-error.AVATAR_DOCUMENT_WRONG_CATEGORY',
    message: 'Категорія документа має бути AVATAR',
  },
  AVATAR_DOCUMENT_WRONG_OWNER: /* i18n */ {
    id: 'api-error.AVATAR_DOCUMENT_WRONG_OWNER',
    message: 'Аватар: документ належить іншому користувачу',
  },
  CANNOT_ARCHIVE_ANOTHER_ADMIN: /* i18n */ {
    id: 'api-error.CANNOT_ARCHIVE_ANOTHER_ADMIN',
    message: 'Не можна заархівувати іншого адміністратора',
  },
  CANNOT_ARCHIVE_YOURSELF: /* i18n */ {
    id: 'api-error.CANNOT_ARCHIVE_YOURSELF',
    message: 'Не можна заархівувати самого себе',
  },
  CANNOT_EDIT_ANOTHER_ADMIN: /* i18n */ {
    id: 'api-error.CANNOT_EDIT_ANOTHER_ADMIN',
    message: 'Не можна редагувати обліковий запис іншого адміністратора',
  },
  CANNOT_REMOVE_LAST_ROLE_MEMBER: /* i18n */ {
    id: 'api-error.CANNOT_REMOVE_LAST_ROLE_MEMBER',
    message: 'Не можна прибрати останнього учасника цієї ролі з проєкту',
  },
  DROP_ARCHIVED: /* i18n */ {
    id: 'api-error.DROP_ARCHIVED',
    message: 'Дропа вже заархівовано',
  },
  DROP_ARCHIVE_ADMIN_ONLY: /* i18n */ {
    id: 'api-error.DROP_ARCHIVE_ADMIN_ONLY',
    message: 'Архівація дропа доступна лише адміністратору',
  },
  DROP_CREATE_ADMIN_ONLY: /* i18n */ {
    id: 'api-error.DROP_CREATE_ADMIN_ONLY',
    message: 'Створення дропа доступне лише адміністратору',
  },
  DROP_CREATE_VIA_DEDICATED_ENDPOINT: /* i18n */ {
    id: 'api-error.DROP_CREATE_VIA_DEDICATED_ENDPOINT',
    message: 'Створення DROP доступне лише через POST /api/users/drops',
  },
  DROP_NOT_FOUND: /* i18n */ {
    id: 'api-error.DROP_NOT_FOUND',
    message: 'Дропа не знайдено',
  },
  DROP_PROJECT_ACCESS_DENIED: /* i18n */ {
    id: 'api-error.DROP_PROJECT_ACCESS_DENIED',
    message: 'Доступ заборонено: drop-проєкти доступні лише ролі DROP',
  },
  DROP_ROLE_CHANGE_VIA_DEDICATED_ENDPOINT: /* i18n */ {
    id: 'api-error.DROP_ROLE_CHANGE_VIA_DEDICATED_ENDPOINT',
    message: 'Зміна ролі на DROP доступна лише через POST /api/users/drops',
  },
  DROP_SHARE_OVERRIDE_FORBIDDEN: /* i18n */ {
    id: 'api-error.DROP_SHARE_OVERRIDE_FORBIDDEN',
    message: 'Змінити перевизначення частки дропа може лише ADMIN або ACCOUNTANT',
  },
  DROP_TEAM_ID_REQUIRED: /* i18n */ {
    id: 'api-error.DROP_TEAM_ID_REQUIRED',
    message: 'dropTeamId обов’язковий при teamMode=JOIN_DROP_TEAM',
  },
  EMAIL_ALREADY_IN_USE: /* i18n */ {
    id: 'api-error.EMAIL_ALREADY_IN_USE',
    message: 'Ця адреса вже використовується. Введіть іншу',
  },
  EMAIL_NOT_AUTHORIZED: /* i18n */ {
    id: 'api-error.EMAIL_NOT_AUTHORIZED',
    message: 'Ця електронна адреса не має доступу',
  },
  EMAIL_TAKEN_BY_ANOTHER_USER: /* i18n */ {
    id: 'api-error.EMAIL_TAKEN_BY_ANOTHER_USER',
    message: 'Ця адреса вже зайнята іншим користувачем',
  },
  GOOGLE_ACCOUNT_MISMATCH: /* i18n */ {
    id: 'api-error.GOOGLE_ACCOUNT_MISMATCH',
    message: 'Обліковий запис Google не збігається',
  },
  GOOGLE_CREDENTIAL_INVALID: /* i18n */ {
    id: 'api-error.GOOGLE_CREDENTIAL_INVALID',
    message: 'Недійсні облікові дані Google',
  },
  HR_JOIN_OWN_DROP_TEAM_ONLY: /* i18n */ {
    id: 'api-error.HR_JOIN_OWN_DROP_TEAM_ONLY',
    message: 'HR може приєднувати синьйора лише до своєї drop-команди',
  },
  HR_REQUIRED_MINIMUM_ONE: /* i18n */ {
    id: 'api-error.HR_REQUIRED_MINIMUM_ONE',
    message: 'Потрібен щонайменше один HR',
  },
  HR_SENIOR_ONLY_CREATION: /* i18n */ {
    id: 'api-error.HR_SENIOR_ONLY_CREATION',
    message: 'HR може створювати лише синьйорів',
  },
  IMPERSONATION_ALREADY_ACTIVE: /* i18n */ {
    id: 'api-error.IMPERSONATION_ALREADY_ACTIVE',
    message: 'Не можна почати нове входження від чужого імені, поки триває інше',
  },
  IMPERSONATION_NOT_ACTIVE: /* i18n */ {
    id: 'api-error.IMPERSONATION_NOT_ACTIVE',
    message: 'Активного входження від чужого імені немає',
  },
  IMPERSONATION_ORIGIN_UNAVAILABLE: /* i18n */ {
    id: 'api-error.IMPERSONATION_ORIGIN_UNAVAILABLE',
    message: 'Початковий адміністратор недоступний',
  },
  IMPERSONATION_SELF_FORBIDDEN: /* i18n */ {
    id: 'api-error.IMPERSONATION_SELF_FORBIDDEN',
    message: 'Не можна увійти від імені самого себе',
  },
  IMPERSONATION_TARGET_ADMIN_FORBIDDEN: /* i18n */ {
    id: 'api-error.IMPERSONATION_TARGET_ADMIN_FORBIDDEN',
    message: 'Не можна увійти від імені іншого адміністратора',
  },
  INVITE_ALREADY_USED: /* i18n */ {
    id: 'api-error.INVITE_ALREADY_USED',
    message: 'Запрошення вже використано',
  },
  INVITE_EXPIRED: /* i18n */ {
    id: 'api-error.INVITE_EXPIRED',
    message: 'Термін дії запрошення закінчився',
  },
  INVITE_GOOGLE_ACCOUNT_MISMATCH: /* i18n */ {
    id: 'api-error.INVITE_GOOGLE_ACCOUNT_MISMATCH',
    message: 'Обліковий запис Google не збігається з адресою запрошення',
  },
  INVITE_INVALID: /* i18n */ {
    id: 'api-error.INVITE_INVALID',
    message: 'Запрошення недійсне',
  },
  JOIN_DROP_TEAM_SENIOR_ONLY: /* i18n */ {
    id: 'api-error.JOIN_DROP_TEAM_SENIOR_ONLY',
    message: 'teamMode=JOIN_DROP_TEAM доступний лише під час створення SENIOR',
  },
  JUNIOR_ALREADY_ON_ANOTHER_PROJECT: /* i18n */ {
    id: 'api-error.JUNIOR_ALREADY_ON_ANOTHER_PROJECT',
    message: 'Джуніор уже є активним учасником іншого проєкту',
  },
  LOGO_DOCUMENT_DELETED: /* i18n */ {
    id: 'api-error.LOGO_DOCUMENT_DELETED',
    message: 'Логотип: документ видалено',
  },
  LOGO_DOCUMENT_NOT_FOUND: /* i18n */ {
    id: 'api-error.LOGO_DOCUMENT_NOT_FOUND',
    message: 'Логотип: документ не знайдено',
  },
  LOGO_DOCUMENT_WRONG_CATEGORY: /* i18n */ {
    id: 'api-error.LOGO_DOCUMENT_WRONG_CATEGORY',
    message: 'Категорія документа має бути LOGO',
  },
  LOGO_DOCUMENT_WRONG_PROJECT: /* i18n */ {
    id: 'api-error.LOGO_DOCUMENT_WRONG_PROJECT',
    message: 'Логотип: документ належить іншому проєкту',
  },
  METHOD_DROP_ONLY: /* i18n */ {
    id: 'api-error.METHOD_DROP_ONLY',
    message: 'Метод доступний лише для DROP',
  },
  NO_HR_CONTACT_ACCESS: /* i18n */ {
    id: 'api-error.NO_HR_CONTACT_ACCESS',
    message: 'Немає доступу до контакту HR',
  },
  PAYMENT_TYPE_CHANGE_FORBIDDEN: /* i18n */ {
    id: 'api-error.PAYMENT_TYPE_CHANGE_FORBIDDEN',
    message: 'Змінити тип оплати проєкту може лише ADMIN або ACCOUNTANT',
  },
  PERSONAL_EMAIL_ALREADY_VERIFIED: /* i18n */ {
    id: 'api-error.PERSONAL_EMAIL_ALREADY_VERIFIED',
    message: 'Особисту адресу вже підтверджено — повторне запрошення не потрібне',
  },
  PERSONAL_EMAIL_MUST_DIFFER_FROM_WORK: /* i18n */ {
    id: 'api-error.PERSONAL_EMAIL_MUST_DIFFER_FROM_WORK',
    message: 'Особиста адреса має відрізнятися від робочої',
  },
  PERSONAL_EMAIL_NOT_SET: /* i18n */ {
    id: 'api-error.PERSONAL_EMAIL_NOT_SET',
    message: 'У користувача не вказано особисту адресу',
  },
  PROJECT_ALREADY_ARCHIVED: /* i18n */ {
    id: 'api-error.PROJECT_ALREADY_ARCHIVED',
    message: 'Проєкт уже заархівовано',
  },
  PROJECT_HAS_ACTIVE_JUNIOR: /* i18n */ {
    id: 'api-error.PROJECT_HAS_ACTIVE_JUNIOR',
    message: 'У проєкту вже є активний джуніор',
  },
  PROJECT_MEMBER_ROLE_RESTRICTED: /* i18n */ {
    id: 'api-error.PROJECT_MEMBER_ROLE_RESTRICTED',
    message: 'Учасниками проєкту можуть бути лише JUNIOR, HR і ACCOUNTANT',
  },
  PROJECT_NOT_ARCHIVED: /* i18n */ {
    id: 'api-error.PROJECT_NOT_ARCHIVED',
    message: 'Проєкт не заархівовано',
  },
  PROJECT_NOT_FOUND: /* i18n */ {
    id: 'api-error.PROJECT_NOT_FOUND',
    message: 'Проєкт не знайдено',
  },
  PROJECT_NOT_IN_YOUR_TEAMS: /* i18n */ {
    id: 'api-error.PROJECT_NOT_IN_YOUR_TEAMS',
    message: 'Проєкт не у ваших командах',
  },
  REJOIN_TEAM_MUST_BE_FORMER_MEMBER: /* i18n */ {
    id: 'api-error.REJOIN_TEAM_MUST_BE_FORMER_MEMBER',
    message: 'Самостійно приєднатися можна лише до команди, в якій ви вже були',
  },
  REJOIN_TEAM_SENIOR_ONLY: /* i18n */ {
    id: 'api-error.REJOIN_TEAM_SENIOR_ONLY',
    message: 'Повторне приєднання до команди доступне лише для SENIOR',
  },
  SENIOR_ADMIN_USDT_ONLY: /* i18n */ {
    id: 'api-error.SENIOR_ADMIN_USDT_ONLY',
    message: 'Синьйор і адміністратор можуть використовувати лише USDT ERC-20',
  },
  SENIOR_NOT_FOUND: /* i18n */ {
    id: 'api-error.SENIOR_NOT_FOUND',
    message: 'Синьйора не знайдено',
  },
  SENIOR_SHARE_OVERRIDE_FORBIDDEN: /* i18n */ {
    id: 'api-error.SENIOR_SHARE_OVERRIDE_FORBIDDEN',
    message: 'Змінити перевизначення частки синьйора може лише ADMIN або ACCOUNTANT',
  },
  SHARE_APPROVE_IMPERSONATION_FORBIDDEN: /* i18n */ {
    id: 'api-error.SHARE_APPROVE_IMPERSONATION_FORBIDDEN',
    message:
      'Поки ви увійшли як інший співробітник, підтвердити його частку не можна — це має зробити він сам',
  },
  SHARE_CANCEL_ADMIN_ACCOUNTANT_ONLY: /* i18n */ {
    id: 'api-error.SHARE_CANCEL_ADMIN_ACCOUNTANT_ONLY',
    message: 'Скасувати пропозицію частки може лише ADMIN або ACCOUNTANT',
  },
  SHARE_CANCEL_ADMIN_ONLY: /* i18n */ {
    id: 'api-error.SHARE_CANCEL_ADMIN_ONLY',
    message: 'Скасувати пропозицію частки може лише ADMIN',
  },
  SHARE_CHANGE_REQUESTER_REQUIRED: /* i18n */ {
    id: 'api-error.SHARE_CHANGE_REQUESTER_REQUIRED',
    message: 'Зміна частки потребує визначеного ініціатора запиту',
  },
  SHARE_REJECT_IMPERSONATION_FORBIDDEN: /* i18n */ {
    id: 'api-error.SHARE_REJECT_IMPERSONATION_FORBIDDEN',
    message:
      'Поки ви увійшли як інший співробітник, відхилити його частку не можна — це має зробити він сам',
  },
  TELEGRAM_CHANNEL_SENIOR_ONLY: /* i18n */ {
    id: 'api-error.TELEGRAM_CHANNEL_SENIOR_ONLY',
    message: 'Telegram-канал можна вказати лише для SENIOR',
  },
  USER_ALREADY_ARCHIVED: /* i18n */ {
    id: 'api-error.USER_ALREADY_ARCHIVED',
    message: 'Користувача вже заархівовано',
  },
  USER_EMAIL_EXISTS: /* i18n */ {
    id: 'api-error.USER_EMAIL_EXISTS',
    message: 'Користувач із такою електронною адресою вже існує',
  },
  USER_NOT_ARCHIVED: /* i18n */ {
    id: 'api-error.USER_NOT_ARCHIVED',
    message: 'Користувача не заархівовано',
  },
  USER_NOT_DROP: /* i18n */ {
    id: 'api-error.USER_NOT_DROP',
    message: 'Користувач не є DROP',
  },
  USER_NOT_FOUND: /* i18n */ {
    id: 'api-error.USER_NOT_FOUND',
    message: 'Користувача не знайдено',
  },
  USER_NOT_SENIOR_OR_ADMIN: /* i18n */ {
    id: 'api-error.USER_NOT_SENIOR_OR_ADMIN',
    message: 'Користувач не є SENIOR або ADMIN',
  },
  WORK_EMAIL_MUST_DIFFER_FROM_PERSONAL: /* i18n */ {
    id: 'api-error.WORK_EMAIL_MUST_DIFFER_FROM_PERSONAL',
    message: 'Робоча адреса має відрізнятися від особистої',
  },
}

export const AUTH_USERS_PROJECTS_ERROR_FALLBACK_EN: Record<AuthUsersProjectsErrorCode, string> = {
  ACCOUNT_DISABLED: 'Account disabled',
  ACTIVE_MEMBER_NOT_FOUND: 'Active member not found in the project',
  ADMIN_CANNOT_CHANGE_OWN_ROLE: "An admin can't change their own role",
  ADMIN_CREATION_FORBIDDEN: 'Creating an ADMIN is forbidden — the pool is fixed',
  ADMIN_ROLE_ASSIGNMENT_FORBIDDEN: 'Assigning the ADMIN role is forbidden — the pool is fixed',
  ALREADY_ACTIVE_PROJECT_MEMBER: 'The user is already an active member of this project',
  ALREADY_HAS_ACTIVE_TEAM: 'You already have an active team',
  ARCHIVED_USER_CANNOT_JOIN_PROJECT: "The user is archived — they can't be added to the project",
  AVATAR_DOCUMENT_DELETED: 'Avatar: document deleted',
  AVATAR_DOCUMENT_NOT_FOUND: 'Avatar: document not found',
  AVATAR_DOCUMENT_WRONG_CATEGORY: 'The document category must be AVATAR',
  AVATAR_DOCUMENT_WRONG_OWNER: 'Avatar: document belongs to another user',
  CANNOT_ARCHIVE_ANOTHER_ADMIN: "You can't archive another admin",
  CANNOT_ARCHIVE_YOURSELF: "You can't archive yourself",
  CANNOT_EDIT_ANOTHER_ADMIN: "You can't edit another admin's account",
  CANNOT_REMOVE_LAST_ROLE_MEMBER: 'Cannot remove the last member of this role from the project',
  DROP_ARCHIVED: 'The drop is already archived',
  DROP_ARCHIVE_ADMIN_ONLY: 'Only an admin can archive a drop',
  DROP_CREATE_ADMIN_ONLY: 'Only an admin can create a drop',
  DROP_CREATE_VIA_DEDICATED_ENDPOINT: 'Creating a DROP is only available via POST /api/users/drops',
  DROP_NOT_FOUND: 'Drop not found',
  DROP_PROJECT_ACCESS_DENIED: 'Access denied: drop projects are only available to the DROP role',
  DROP_ROLE_CHANGE_VIA_DEDICATED_ENDPOINT:
    'Changing the role to DROP is only available via POST /api/users/drops',
  DROP_SHARE_OVERRIDE_FORBIDDEN:
    "Only ADMIN or ACCOUNTANT can change the drop's share percent override",
  DROP_TEAM_ID_REQUIRED: 'dropTeamId is required when teamMode=JOIN_DROP_TEAM',
  EMAIL_ALREADY_IN_USE: 'This email is already in use. Enter a different one',
  EMAIL_NOT_AUTHORIZED: 'This email is not authorized',
  EMAIL_TAKEN_BY_ANOTHER_USER: 'This email is already taken by another user',
  GOOGLE_ACCOUNT_MISMATCH: 'Google account mismatch',
  GOOGLE_CREDENTIAL_INVALID: 'Invalid Google credential',
  HR_JOIN_OWN_DROP_TEAM_ONLY: 'HR can only add a senior to their own drop team',
  HR_REQUIRED_MINIMUM_ONE: 'At least one HR is required',
  HR_SENIOR_ONLY_CREATION: 'HR can only create seniors',
  IMPERSONATION_ALREADY_ACTIVE: "You can't start another impersonation while one is already active",
  IMPERSONATION_NOT_ACTIVE: 'No active impersonation',
  IMPERSONATION_ORIGIN_UNAVAILABLE: 'The original admin is unavailable',
  IMPERSONATION_SELF_FORBIDDEN: "You can't impersonate yourself",
  IMPERSONATION_TARGET_ADMIN_FORBIDDEN: "You can't impersonate another admin",
  INVITE_ALREADY_USED: 'The invite has already been used',
  INVITE_EXPIRED: 'The invite has expired',
  INVITE_GOOGLE_ACCOUNT_MISMATCH: "The Google account doesn't match the invited address",
  INVITE_INVALID: 'The invite is invalid',
  JOIN_DROP_TEAM_SENIOR_ONLY: 'teamMode=JOIN_DROP_TEAM is only available when creating a SENIOR',
  JUNIOR_ALREADY_ON_ANOTHER_PROJECT: 'The junior is already an active member of another project',
  LOGO_DOCUMENT_DELETED: 'Logo: document deleted',
  LOGO_DOCUMENT_NOT_FOUND: 'Logo: document not found',
  LOGO_DOCUMENT_WRONG_CATEGORY: 'The document category must be LOGO',
  LOGO_DOCUMENT_WRONG_PROJECT: 'Logo: document belongs to another project',
  METHOD_DROP_ONLY: 'This method is only available for DROP',
  NO_HR_CONTACT_ACCESS: 'No access to the HR contact',
  PAYMENT_TYPE_CHANGE_FORBIDDEN: "Only ADMIN or ACCOUNTANT can change the project's payment type",
  PERSONAL_EMAIL_ALREADY_VERIFIED:
    'The personal email is already verified — a repeat invite is not needed',
  PERSONAL_EMAIL_MUST_DIFFER_FROM_WORK: 'The personal email must be different from the work email',
  PERSONAL_EMAIL_NOT_SET: 'The user has no personal email set',
  PROJECT_ALREADY_ARCHIVED: 'The project is already archived',
  PROJECT_HAS_ACTIVE_JUNIOR: 'The project already has an active junior member',
  PROJECT_MEMBER_ROLE_RESTRICTED: 'Only JUNIOR, HR, and ACCOUNTANT can be added as project members',
  PROJECT_NOT_ARCHIVED: 'The project is not archived',
  PROJECT_NOT_FOUND: 'Project not found',
  PROJECT_NOT_IN_YOUR_TEAMS: 'The project is not in your teams',
  REJOIN_TEAM_MUST_BE_FORMER_MEMBER: 'You can only rejoin a team you were previously a member of',
  REJOIN_TEAM_SENIOR_ONLY: 'Rejoining a team is available only for SENIOR',
  SENIOR_ADMIN_USDT_ONLY: 'Senior and admin can only use USDT ERC-20',
  SENIOR_NOT_FOUND: 'Senior not found',
  SENIOR_SHARE_OVERRIDE_FORBIDDEN:
    "Only ADMIN or ACCOUNTANT can change the senior's share percent override",
  SHARE_APPROVE_IMPERSONATION_FORBIDDEN:
    "While you're impersonating another employee, you can't approve their share — only they can",
  SHARE_CANCEL_ADMIN_ACCOUNTANT_ONLY: 'Only ADMIN or ACCOUNTANT can cancel a share proposal',
  SHARE_CANCEL_ADMIN_ONLY: 'Only ADMIN can cancel a share proposal',
  SHARE_CHANGE_REQUESTER_REQUIRED: 'Changing the share requires a specific requester',
  SHARE_REJECT_IMPERSONATION_FORBIDDEN:
    "While you're impersonating another employee, you can't reject their share — only they can",
  TELEGRAM_CHANNEL_SENIOR_ONLY: 'A Telegram channel can only be set for SENIOR users',
  USER_ALREADY_ARCHIVED: 'User is already archived',
  USER_EMAIL_EXISTS: 'A user with this email already exists',
  USER_NOT_ARCHIVED: 'User is not archived',
  USER_NOT_DROP: 'The user is not a DROP',
  USER_NOT_FOUND: 'User not found',
  USER_NOT_SENIOR_OR_ADMIN: 'The user is not a SENIOR or ADMIN',
  WORK_EMAIL_MUST_DIFFER_FROM_PERSONAL: 'The work email must be different from the personal email',
}
