import { useId, useRef } from 'react'
import { motion } from 'framer-motion'
import { type LucideIcon } from 'lucide-react'
import { cn } from '@/lib/utils'

/**
 * SegmentedToggle — reusable iOS-style segmented control with a sliding
 * gold pill (`motion.div layoutId`) marking the active option.
 *
 * Used wherever a user picks one option out of a small (2-4) mutually
 * exclusive set: payment method, sort direction, partner filter, etc.
 *
 * Reference impl (this generalises the pattern):
 *   apps/web/app/components/users/UserDialog.tsx (payment method, PR #33)
 *   apps/web/app/routes/crm/users/index.tsx (users list layout)
 *
 * Accessibility:
 *   - role="radiogroup" on the container with provided `ariaLabel`
 *   - role="radio" + `aria-checked` on each button
 *   - Buttons are real <button type="button"> so keyboard Enter/Space works
 *   - Disabled propagates to all buttons
 */

export interface SegmentedToggleOption<V extends string> {
  value: V
  /**
   * Display label rendered to the user. Should be a meaningful non-empty
   * string. For icon-only buttons, pass an empty string and supply
   * `ariaLabel` for screen readers — otherwise the enum value leaks into
   * the accessible name.
   */
  label: string
  /** Optional Lucide icon shown to the left of the label */
  icon?: LucideIcon
  /**
   * Override for the button's accessible name. Use when `label` is empty
   * (icon-only) or when the visible text isn't descriptive enough for
   * screen readers (e.g. raw enum spelling like "USDT_ERC20").
   */
  ariaLabel?: string
  /** Optional per-option test id suffix; defaults to value */
  testIdSuffix?: string
  /**
   * Full override for the button's `data-testid`. When set, this exact value
   * is used as the test id — independent of the container's `testId`. Use
   * for E2E selectors that pre-date SegmentedToggle adoption (e.g.
   * `toggle-archived-projects`) so existing specs continue to work.
   */
  testId?: string
  /** Per-option disabled state (e.g. role-restricted option) */
  disabled?: boolean
}

export interface SegmentedToggleProps<V extends string> {
  value: V
  onChange: (value: V) => void
  options: ReadonlyArray<SegmentedToggleOption<V>>
  ariaLabel: string
  /**
   * Unique layoutId scope. When multiple SegmentedToggles render on the
   * same page, each must pass a unique value so the sliding pills don't
   * cross-fade between unrelated toggles. Defaults to an autogenerated
   * React id, which is safe but harms cross-render continuity.
   */
  layoutId?: string
  className?: string
  /** Disable the entire toggle (in addition to per-option disabled flags). */
  disabled?: boolean
  size?: 'sm' | 'md'
  /**
   * Visual style:
   * - 'pill' (default) — subtle muted track, primary/15 active pill. Use
   *   for inline selectors within forms / panels (payment method, sort).
   * - 'tabs' — page-level segmented tabs. Track is the same muted card-like
   *   surface, but the *active* pill is a more saturated primary tint
   *   (primary/25 background + primary/50 border) so the tabs feel like a
   *   focal page control, not a tucked-away helper.
   */
  variant?: 'pill' | 'tabs'
  /**
   * ARIA role for the container.
   * - 'radiogroup' (default) — picks one option out of a small set; pairs
   *   with role="radio" on each button. Matches the "pill" variant intent.
   * - 'tablist' — page-level tabs; pairs with role="tab" + aria-selected
   *   on each button. Use with variant="tabs" for semantic correctness.
   */
  role?: 'radiogroup' | 'tablist'
  /** Test id on the container; per-button test ids are `${testId}-${value}`. */
  testId?: string
}

export function SegmentedToggle<V extends string>({
  value,
  onChange,
  options,
  ariaLabel,
  layoutId,
  className,
  disabled = false,
  size = 'md',
  variant = 'pill',
  role,
  testId,
}: SegmentedToggleProps<V>) {
  // Auto-generate a layoutId when caller doesn't supply one. We use a ref so
  // the value is stable across re-renders within a single mount lifecycle.
  const autoId = useId()
  const layoutIdRef = useRef(layoutId ?? `segmented-toggle-${autoId}`)
  const pillLayoutId = layoutId ?? layoutIdRef.current

  const sizeStyles = size === 'sm' ? 'px-2 py-1 text-xs gap-1.5' : 'px-3 py-2 text-sm gap-2'

  // 'tabs' variant uses a more saturated active pill so page-level segmented
  // tabs read as a focal control (vs the subtle in-form 'pill' default).
  const activePillStyles =
    variant === 'tabs'
      ? 'bg-primary/25 border border-primary/50 shadow-sm'
      : 'bg-primary/15 border border-primary/40 shadow-sm'

  const containerRole = role ?? (variant === 'tabs' ? 'tablist' : 'radiogroup')
  const itemRole = containerRole === 'tablist' ? 'tab' : 'radio'

  return (
    <div
      role={containerRole}
      aria-label={ariaLabel}
      aria-disabled={disabled || undefined}
      data-testid={testId}
      className={cn(
        'relative grid gap-1 overflow-hidden rounded-lg border border-border bg-muted/60 p-1',
        className,
      )}
      style={{ gridTemplateColumns: `repeat(${options.length}, minmax(0, 1fr))` }}
    >
      {options.map((option) => {
        const Icon = option.icon
        const active = option.value === value
        const buttonDisabled = disabled || option.disabled === true
        const suffix = option.testIdSuffix ?? option.value
        return (
          <button
            key={option.value}
            type="button"
            role={itemRole}
            {...(itemRole === 'tab' ? { 'aria-selected': active } : { 'aria-checked': active })}
            // Prefer explicit ariaLabel (icon-only / opaque enums), then visible label,
            // then enum value as a last-resort fallback so screen-reader users
            // always have *some* name even if a caller mis-configures the option.
            aria-label={option.ariaLabel ?? (option.label || option.value)}
            disabled={buttonDisabled}
            onClick={() => {
              if (buttonDisabled) return
              if (option.value === value) return
              onChange(option.value)
            }}
            data-testid={option.testId ?? (testId ? `${testId}-${suffix}` : undefined)}
            className={cn(
              'relative flex items-center justify-center rounded-md',
              'transition-colors duration-150 focus:outline-none',
              'focus-visible:ring-1 focus-visible:ring-primary/50',
              sizeStyles,
              'font-medium',
              active ? 'text-foreground' : 'text-muted-foreground hover:text-foreground',
              buttonDisabled && 'cursor-not-allowed opacity-50 hover:text-muted-foreground',
            )}
          >
            {active && (
              <motion.div
                layoutId={pillLayoutId}
                className={cn('absolute inset-0 rounded-md', activePillStyles)}
                transition={{ type: 'spring', stiffness: 380, damping: 32 }}
                aria-hidden
              />
            )}
            <span className="relative z-10 flex items-center gap-2">
              {Icon && (
                <Icon
                  className={cn(
                    size === 'sm' ? 'h-3.5 w-3.5' : 'h-4 w-4',
                    active && 'text-primary',
                  )}
                />
              )}
              {option.label ? <span>{option.label}</span> : null}
            </span>
          </button>
        )
      })}
    </div>
  )
}
