import { useId, useRef } from 'react'
import type { KeyboardEvent as ReactKeyboardEvent } from 'react'
import { motion } from 'framer-motion'
import { type LucideIcon } from 'lucide-react'
import { cn } from '@/lib/utils'

/**
 * SegmentedToggle — reusable iOS-style segmented control with a sliding
 * gold pill (`motion.div layoutId`) marking the active option.
 *
 * Used wherever a user picks one option out of a small (2-4) mutually
 * exclusive set: payment method, sort direction, partner filter, etc.
 *
 * Reference impl (this generalises the pattern):
 *   apps/web/app/components/users/UserDialog.tsx (payment method, PR #33)
 *   apps/web/app/routes/_authenticated/users/index.tsx (users list layout)
 *
 * Accessibility:
 *   - role="radiogroup" on the container with provided `ariaLabel`
 *   - role="radio" + `aria-checked` on each button
 *   - Buttons are real <button type="button"> so keyboard Enter/Space works
 *   - Disabled propagates to all buttons
 *   - `itemRole === 'radio'` (i.e. NOT the `variant="tabs"` pairing) follows
 *     the ARIA APG radiogroup pattern: one roving tab stop (`tabIndex={0}`
 *     only on the active option, `-1` on the rest) plus Arrow/Home/End moves
 *     BOTH focus and selection between options (PR #696 fix-round 1,
 *     CR-M-2). `variant="tabs"` keeps every tab independently focusable —
 *     that pairing is unchanged.
 */

export interface SegmentedToggleOption<V extends string> {
  value: V
  /**
   * Display label rendered to the user. Should be a meaningful non-empty
   * string. For icon-only buttons, pass an empty string and supply
   * `ariaLabel` for screen readers — otherwise the enum value leaks into
   * the accessible name.
   */
  label: string
  /** Optional Lucide icon shown to the left of the label */
  icon?: LucideIcon
  /**
   * Override for the button's accessible name. Use when `label` is empty
   * (icon-only) or when the visible text isn't descriptive enough for
   * screen readers (e.g. raw enum spelling like "USDT_ERC20").
   */
  ariaLabel?: string
  /** Optional per-option test id suffix; defaults to value */
  testIdSuffix?: string
  /**
   * Full override for the button's `data-testid`. When set, this exact value
   * is used as the test id — independent of the container's `testId`. Use
   * for E2E selectors that pre-date SegmentedToggle adoption (e.g.
   * `toggle-archived-projects`) so existing specs continue to work.
   */
  testId?: string
  /** Per-option disabled state (e.g. role-restricted option) */
  disabled?: boolean
  /**
   * Override the active pill color for THIS option only (task-crm-vacancies-ui
   * §3.2). Omitted keeps the container's normal pill (gold `activePillStyles`).
   * `'destructive'` renders a red pill instead — used for a single "danger"
   * option inside an otherwise neutral toggle (e.g. candidate application
   * status: «Отклонено» reads as a warning, not just another neutral choice).
   */
  activeVariant?: 'default' | 'destructive'
}

export interface SegmentedToggleProps<V extends string> {
  value: V
  onChange: (value: V) => void
  options: ReadonlyArray<SegmentedToggleOption<V>>
  ariaLabel: string
  /**
   * Unique layoutId scope. When multiple SegmentedToggles render on the
   * same page, each must pass a unique value so the sliding pills don't
   * cross-fade between unrelated toggles. Defaults to an autogenerated
   * React id, which is safe but harms cross-render continuity.
   */
  layoutId?: string
  className?: string
  /** Disable the entire toggle (in addition to per-option disabled flags). */
  disabled?: boolean
  size?: 'sm' | 'md'
  /**
   * Visual style:
   * - 'pill' (default) — subtle muted track, primary/15 active pill. Use
   *   for inline selectors within forms / panels (payment method, sort).
   * - 'tabs' — page-level segmented tabs. Track is the same muted card-like
   *   surface, but the *active* pill is a more saturated primary tint
   *   (primary/25 background + primary/50 border) so the tabs feel like a
   *   focal page control, not a tucked-away helper.
   */
  variant?: 'pill' | 'tabs'
  /**
   * ARIA role for the container.
   * - 'radiogroup' (default) — picks one option out of a small set; pairs
   *   with role="radio" on each button. Matches the "pill" variant intent.
   * - 'tablist' — page-level tabs; pairs with role="tab" + aria-selected
   *   on each button. Use with variant="tabs" for semantic correctness.
   */
  role?: 'radiogroup' | 'tablist'
  /** Test id on the container; per-button test ids are `${testId}-${value}`. */
  testId?: string
}

export function SegmentedToggle<V extends string>({
  value,
  onChange,
  options,
  ariaLabel,
  layoutId,
  className,
  disabled = false,
  size = 'md',
  variant = 'pill',
  role,
  testId,
}: SegmentedToggleProps<V>) {
  // Auto-generate a layoutId when caller doesn't supply one. We use a ref so
  // the value is stable across re-renders within a single mount lifecycle.
  const autoId = useId()
  const layoutIdRef = useRef(layoutId ?? `segmented-toggle-${autoId}`)
  const pillLayoutId = layoutId ?? layoutIdRef.current
  // Roving-tabindex target for Arrow/Home/End (see keydown handler below) —
  // a live map instead of an array-of-refs so lookup by option value stays
  // O(1) and doesn't depend on render order. Stores `null` on unmount rather
  // than deleting the key: the only read (`.get(...)?.focus()`, in the
  // keydown handler) treats a `null` and a missing entry identically, so
  // branching here would be an untestable if/else with no observable effect
  // — `Map.set` unconditionally is both simpler and has no equivalent mutant.
  const buttonRefs = useRef<Map<V, HTMLButtonElement | null>>(new Map())

  const sizeStyles = size === 'sm' ? 'px-2 py-1 text-xs gap-1.5' : 'px-3 py-2 text-sm gap-2'
  // 44px touch target on mobile only (foundation.md §Тач; responsive-design.md
  // hard-gate) — desktop keeps the existing `py-2` height (UX-M-1, PR #696
  // fix-round 1). `sm` size stays as-is: it's used in denser layouts that
  // don't carry the same mobile touch-target expectation.
  const touchTargetStyles = size === 'md' ? 'min-h-11 sm:min-h-0' : undefined

  // Active pill is the solid brand yellow — same `bg-primary` fill used by
  // Button/Badge default variant (owner request 2026-07-24: the active tab
  // reads as "the" brand yellow, not a translucent tint). 'tabs' keeps a
  // stronger shadow so page-level segmented tabs still read as more focal
  // than the subtle in-form 'pill' default; the fill itself is identical
  // across variants/sizes so yellow application stays consistent.
  const activePillStyles = variant === 'tabs' ? 'bg-primary shadow-md' : 'bg-primary shadow-sm'

  const containerRole = role ?? (variant === 'tabs' ? 'tablist' : 'radiogroup')
  const itemRole = containerRole === 'tablist' ? 'tab' : 'radio'

  // ARIA APG radiogroup keyboard pattern — Left/Up moves to the previous
  // enabled option, Right/Down to the next, Home/End to the first/last;
  // wraps around at the ends. Moves BOTH selection (`onChange`) and focus
  // in one keystroke, matching how native radio groups behave. No-op for
  // `variant="tabs"` (itemRole === 'tab') — each tab keeps its own
  // independent tab stop, unchanged from before this handler existed.
  function handleContainerKeyDown(e: ReactKeyboardEvent<HTMLDivElement>) {
    if (itemRole !== 'radio' || disabled) return
    const enabledOptions = options.filter((o) => o.disabled !== true)
    // No separate `enabledOptions.length === 0` early return — `target`
    // below is already `undefined` in that case (`enabledOptions[NaN]` from
    // `% 0`, or `enabledOptions[-1]`/`enabledOptions[0]` on an empty array),
    // and the `if (!target) return` guard three lines down handles it
    // identically. A second guard that can never diverge from the first is
    // dead code, not defence-in-depth.
    const currentIndex = enabledOptions.findIndex((o) => o.value === value)
    const from = currentIndex === -1 ? 0 : currentIndex

    let targetIndex: number
    switch (e.key) {
      case 'ArrowLeft':
      case 'ArrowUp':
        targetIndex = (from - 1 + enabledOptions.length) % enabledOptions.length
        break
      case 'ArrowRight':
      case 'ArrowDown':
        targetIndex = (from + 1) % enabledOptions.length
        break
      case 'Home':
        targetIndex = 0
        break
      case 'End':
        targetIndex = enabledOptions.length - 1
        break
      default:
        return
    }

    e.preventDefault()
    const target = enabledOptions[targetIndex]
    if (!target) return
    if (target.value !== value) {
      onChange(target.value)
    }
    // Stryker disable next-line OptionalChaining: `target` always comes from
    // `options` (filtered, never a synthetic value), and EVERY option in
    // `options` renders a `<button>` below that registers its ref on mount
    // — `buttonRefs.current.get(target.value)` cannot be `undefined` for a
    // real render. No test can force this branch without faking a ref map
    // no real render would ever produce.
    buttonRefs.current.get(target.value)?.focus()
  }

  return (
    <div
      role={containerRole}
      aria-label={ariaLabel}
      aria-disabled={disabled || undefined}
      data-testid={testId}
      onKeyDown={handleContainerKeyDown}
      className={cn(
        'relative grid gap-1 overflow-hidden rounded-lg border border-border bg-muted/60 p-1',
        className,
      )}
      style={{ gridTemplateColumns: `repeat(${options.length}, minmax(0, 1fr))` }}
    >
      {options.map((option) => {
        const Icon = option.icon
        const active = option.value === value
        const buttonDisabled = disabled || option.disabled === true
        const suffix = option.testIdSuffix ?? option.value
        // Solid `bg-primary` needs near-black `text-primary-foreground` for
        // contrast (measured ~11-12.5:1 via OKLCH->sRGB relative-luminance,
        // both themes — well above WCAG AA 4.5:1). The destructive pill
        // stays translucent (`bg-destructive/20`) so the theme-adaptive
        // `text-foreground` it already used keeps working — only the
        // default pill's contrast pairing changed.
        const activeTextClass =
          option.activeVariant === 'destructive' ? 'text-foreground' : 'text-primary-foreground'
        return (
          <button
            key={option.value}
            ref={(el) => {
              buttonRefs.current.set(option.value, el)
            }}
            type="button"
            role={itemRole}
            {...(itemRole === 'tab' ? { 'aria-selected': active } : { 'aria-checked': active })}
            // Prefer explicit ariaLabel (icon-only / opaque enums), then visible label,
            // then enum value as a last-resort fallback so screen-reader users
            // always have *some* name even if a caller mis-configures the option.
            aria-label={option.ariaLabel ?? (option.label || option.value)}
            // Roving tabindex (radio pairing only, see handleContainerKeyDown
            // above): one tab stop on the active option, the rest excluded
            // from sequential Tab order but still reachable via Arrow/Home/End
            // (and via a direct programmatic `.focus()`, which ignores
            // tabIndex — the existing Enter/Space keyboard tests rely on
            // exactly that). `variant="tabs"` keeps native per-button
            // tabbing (tabIndex left undefined).
            tabIndex={itemRole === 'radio' ? (active ? 0 : -1) : undefined}
            disabled={buttonDisabled}
            onClick={() => {
              if (buttonDisabled) return
              if (option.value === value) return
              onChange(option.value)
            }}
            data-testid={option.testId ?? (testId ? `${testId}-${suffix}` : undefined)}
            className={cn(
              'relative flex items-center justify-center rounded-md',
              'transition-colors duration-150 focus:outline-none',
              // ring-2 + ring-offset-2/background (button.tsx's own focus
              // pattern) — a same-hue ring drawn flush against the border
              // (no offset) visually fuses with the solid yellow active
              // pill (--ring == --primary): zero perceptible gap, so the
              // indicator nearly disappears exactly where it matters most
              // (WCAG 2.2 SC 2.4.11 review, PR #407). The offset punches a
              // background-colored gap between the pill and the ring so it
              // reads as a ring on EVERY fill (yellow, red destructive, or
              // plain track), not just the low-opacity states this used to
              // cover.
              'focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background',
              sizeStyles,
              touchTargetStyles,
              'font-medium',
              active ? activeTextClass : 'text-muted-foreground hover:text-foreground',
              buttonDisabled && 'cursor-not-allowed opacity-50 hover:text-muted-foreground',
            )}
          >
            {active && (
              <motion.div
                layoutId={pillLayoutId}
                className={cn(
                  'absolute inset-0 rounded-md',
                  option.activeVariant === 'destructive'
                    ? 'bg-destructive/20 border border-destructive/40 shadow-sm'
                    : activePillStyles,
                )}
                transition={{ type: 'spring', stiffness: 380, damping: 32 }}
                aria-hidden
              />
            )}
            <span className="relative z-10 flex items-center gap-2">
              {Icon && (
                <Icon
                  className={cn(
                    size === 'sm' ? 'h-3.5 w-3.5' : 'h-4 w-4',
                    // Match the label's active color, not a hardcoded
                    // `text-primary` — on the old translucent pill a yellow
                    // icon read as an accent, but on the new solid-yellow
                    // fill it would vanish into the background.
                    active && activeTextClass,
                  )}
                />
              )}
              {option.label ? <span>{option.label}</span> : null}
            </span>
          </button>
        )
      })}
    </div>
  )
}
