/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// !!!! WARNING: This file is a PLACEHOLDER. Run `pnpm --filter @crm/landing dev` or `pnpm --filter @crm/landing build` to generate the real route tree. !!!!

import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'

const IndexRouteWithParent = IndexRoute.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as never)

export interface FileRoutesByPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof IndexRoute
    parentRoute: typeof rootRoute
  }
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRouteWithParent
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRouteWithParent,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addRouteChildren(
  rootRouteChildren,
)
