// apps/e2e/fixtures/catalog.ts
// fix-round 1 (PR #697, SPEC-H-1). `apps/e2e` sees neither `@crm/shared` nor
// `@crm/shared-i18n-locales` (both are Vite aliases of `apps/web`; `apps/e2e`
// does not go through Vite at all). The compiled catalog is a flat object
// with no imports of its own, so a plain relative file import reads it
// without a bundler (requires `pnpm i18n:compile` before the run — already
// part of every Task-Step's command order).
import { join } from 'node:path'

const LOCALES_DIR = join(__dirname, '../../../packages/shared/src/i18n/locales')

/**
 * Compiled catalog for `locale`: message id (a hash of the source text —
 * generated by `lingui extract`, NOT the text itself, see
 * https://lingui.dev/guides/explicit-vs-generated-ids) -> localized string.
 * The id for a NEW assertion: run `pnpm i18n:extract`, then
 * `grep -B2 'msgstr "<source uk text>"' packages/shared/src/i18n/locales/uk/messages.po`.
 */
export async function loadMessages(locale: 'uk' | 'en'): Promise<Record<string, string>> {
  const mod = (await import(join(LOCALES_DIR, locale, 'messages'))) as {
    messages: Record<string, string>
  }
  return mod.messages
}
