-- =============================================================================
-- non_deleted_transactions VIEW — prod DDL (manual apply)
-- =============================================================================
--
-- Context
-- -------
-- security-review PR #456 round 2 (verdict BLOCK on 4834458611/4840207923).
-- The round-1 fix (deleted_at/deleted_by/deletion_reason columns +
-- transaction-visibility.util.ts guard FUNCTIONS + a text-scanning regression
-- spec meant to catch a caller who forgot to call them) was defeated 7/7 by
-- the round-2 review: a second unguarded read sharing a guarded function's
-- scan window, a bare `deletedAt` substring inside a COMMENT, `.rightJoin`/
-- `alias()`/nested relational reads the scanner's pattern list never
-- enumerated, and — most importantly — the guard call itself was DELETED
-- from `getDepositStatus` while the explaining comment was left behind; the
-- scanner stayed green throughout.
--
-- This view is the "eliminate, don't detect" fix the round-2 review asked
-- for: `SELECT * FROM non_deleted_transactions` cannot return a soft-deleted
-- row — there is no WHERE clause a caller could omit, because the filter is
-- the view's FROM target, not a condition applied after the fact. Combined
-- with an ESLint `no-restricted-imports` rule banning the raw `transactions`
-- table import outside `apps/api/src/finance/**`, a module like `invoices/`
-- or `documents/` can no longer reach an unfiltered row for its list/
-- aggregate/join reads at all — not "is expected not to", structurally
-- cannot (the raw table is not an importable symbol there, and even if it
-- were, `db.update(nonDeletedTransactions)` does not typecheck — Drizzle
-- views do not satisfy the `PgTable` shape `.update()`/`.insert()`/
-- `.delete()` require).
--
-- Read-only by construction: `non_deleted_transactions` is a simple,
-- single-table, unaggregated view — Postgres would in principle treat it as
-- auto-updatable, but nothing in this codebase writes through it (enforced
-- at the TypeScript layer per above); it is named/documented as read-only.
--
-- How to apply
-- ------------
--   docker compose -f docker-compose.prod.yml exec -T postgres psql \
--     -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1 \
--     < apps/api/drizzle/manual/2026-08-03_non_deleted_transactions_view.sql
--
-- DEPENDENCY (DevOps zone, NOT wired by this PR): see the "Dependency for
-- DevOps" note in the PR body — same pattern as
-- 2026-08-01_transaction_soft_delete.sql, which this view depends on
-- (deleted_at must already exist). Apply AFTER that migration, same deploy.
--
-- Idempotent: `CREATE OR REPLACE VIEW` — safe to re-run any number of times,
-- on every deploy, forever. `CREATE OR REPLACE VIEW` cannot change the
-- output column list of an existing view (Postgres restriction) — if a
-- future column is added to `transactions`, this view picks it up
-- automatically on next apply since it selects `*`; if a column is ever
-- REMOVED or RENAMED, `CREATE OR REPLACE` will fail loudly (ON_ERROR_STOP=1)
-- rather than silently drifting — the correct failure mode.
-- =============================================================================

CREATE OR REPLACE VIEW non_deleted_transactions AS
SELECT * FROM transactions WHERE deleted_at IS NULL;

-- =============================================================================
-- VERIFY (after applying):
--   SELECT viewname FROM pg_views WHERE viewname = 'non_deleted_transactions';
--   SELECT count(*) FROM non_deleted_transactions; -- must equal
--     SELECT count(*) FROM transactions WHERE deleted_at IS NULL;
-- =============================================================================
--
-- Rollback (feature-level; only if this feature is being reverted entirely):
--   DROP VIEW IF EXISTS non_deleted_transactions;
-- =============================================================================
