-- =============================================================================
-- Drop unused users.usr_record column — prod DDL (manual apply)
-- =============================================================================
--
-- Context
-- -------
-- PR #345 (refactor(users,contracts): remove usrRecord field full-stack,
-- merged 2026-07-11) removed the `usrRecord` field and the `{{usrRecord}}`
-- contract variable from ALL code — Drizzle schema (schema.ts), API, web, and
-- contract templates. The code no longer reads or writes this column.
--
-- The physical DB column `users.usr_record` still exists in dev and prod as a
-- now-unused, harmless extra column. drizzle-kit push does NOT drop columns that
-- disappear from the schema (destructive-by-default guard), and the prod image
-- does not ship drizzle-kit anyway. This script finishes the removal — pure DB
-- hygiene, no behaviour change.
--
-- How to apply
-- ------------
-- From the VPS (or any host with Docker access to the prod stack):
--
--   docker compose -f docker-compose.prod.yml exec -T postgres psql \
--     -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1 \
--     < apps/api/drizzle/manual/2026-07-11_drop_usr_record.sql
--
-- Applied automatically on the next deploy — see .github/workflows/deploy.yml
-- ("Pull, up, migrate, health-check" step, Step 2b).
--
-- The statement is FULLY IDEMPOTENT (DROP COLUMN IF EXISTS) — re-running it on a
-- database where the column is already gone is a safe no-op.
-- =============================================================================

ALTER TABLE users DROP COLUMN IF EXISTS usr_record;

-- =============================================================================
-- VERIFY: after applying, this query should return 0 rows.
-- =============================================================================
-- SELECT column_name
--   FROM information_schema.columns
--  WHERE table_name = 'users' AND column_name = 'usr_record';
-- Expected: 0 rows.
-- =============================================================================
