-- =============================================================================
-- Obligation company-name snapshot column — prod DDL (manual apply)
-- task-drop-sees-own-obligations (security-review PR #523 round 1, MED-4)
-- =============================================================================
--
-- Context
-- -------
-- `getDropSelfIncomes` (GET /api/finance/drop/me/incomes) now also returns
-- DROP_PENDING_PAYOUT / PAYOUT_DROP obligation rows (task-drop-sees-own-
-- obligations, PR #523) alongside the old self-declared DROP_INCOME model.
-- Those obligation rows' `senderLabel` is always the literal 'COMPANY' marker
-- (other code branches on that exact string — see the column comment on
-- `transactions.companyNameSnapshot` in schema.ts), so the feed resolved
-- `companyName` for them via a LIVE join to `projects.companyName`. A live
-- join means renaming a project later silently rewrites what a drop reads as
-- the history of money already booked under the OLD name — the one thing a
-- money-history view must never do.
--
-- This column is the fix: `bookCompanyObligations` now stamps
-- `projects.companyName` onto BOTH the senior and the drop IOU it books, at
-- booking time, once, frozen forever — the exact same "snapshot at creation"
-- contract `drop_share_percent` / `senior_share_percent` already use on this
-- same row, applied to the display name instead of a money figure. See the
-- column comment in apps/api/src/database/schema.ts for the full reasoning.
--
-- REQUIRED companion step — re-apply the `non_deleted_transactions` view.
-- ------------------------------------------------------------------------
-- `non_deleted_transactions` (2026-08-03_non_deleted_transactions_view.sql)
-- is `CREATE OR REPLACE VIEW ... AS SELECT * FROM transactions WHERE
-- deleted_at IS NULL`. Postgres does NOT retroactively add a newly-created
-- base-table column to an EXISTING view automatically — even with `SELECT *`
-- — until the view is explicitly re-applied. Discovered the hard way while
-- verifying THIS file on crm_qa: every finance read that goes through the
-- view (getAdminBalance / getSeniorBalance / getTotalEarned /
-- getOwnSalaryStatus, all in apps/api/src/finance/balance.service.ts +
-- salary-status.helper.ts) started failing with
-- `error: column "company_name_snapshot" does not exist` — NOT because the
-- column was missing (it was there, on `transactions`), but because the VIEW
-- still had the old, narrower column list baked in from its last apply.
--
-- Apply order on EVERY environment (dev/crm_qa/prod), always both, always in
-- this order:
--   1. THIS file (adds the column to the base table).
--   2. apps/api/drizzle/manual/2026-08-03_non_deleted_transactions_view.sql
--      (re-`CREATE OR REPLACE VIEW` — picks the new column up because it is
--      `SELECT *`; the file's own header already predicted this exact case:
--      "if a future column is added to transactions, this view picks it up
--      automatically on next apply").
--
-- How to apply
-- ------------
--   docker compose -f docker-compose.prod.yml exec -T postgres psql \
--     -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1 \
--     < apps/api/drizzle/manual/2026-08-12_drop_obligation_company_name_snapshot.sql
--   docker compose -f docker-compose.prod.yml exec -T postgres psql \
--     -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1 \
--     < apps/api/drizzle/manual/2026-08-03_non_deleted_transactions_view.sql
--
-- REQUIRED DevOps wiring (this PR does NOT touch .github/workflows/** —
-- Coder zone-of-write; called out explicitly in this PR's body). Add THIS
-- file to deploy.yml's "Copy compose files and DDL via SCP" `source:` list
-- AND to the migrate step — immediately followed by a re-apply of
-- `2026-08-03_non_deleted_transactions_view.sql` (see above; it is likely
-- ALREADY wired from its own original PR, but confirm it re-RUNS on this
-- deploy too, not just exists in the source list) — applied BEFORE the new
-- api image serves traffic (the api writes this column on every
-- `bookCompanyObligations` call once this PR's code lands, AND every
-- balance/salary read goes through the view — either gap 500s real traffic).
-- `scripts/devops/check-prod-ddl-wiring.py` fails the build until the column
-- file is wired — by design, same as
-- `2026-08-12_admin_income_drop_backfill_column.sql`. It cannot detect the
-- view-re-apply requirement (that script checks file-is-referenced, not
-- inter-file ordering/dependency) — called out here and in the PR body so a
-- human catches it.
--
-- Idempotent: ADD COLUMN IF NOT EXISTS, safe to re-run on every deploy,
-- forever. NULLABLE, NO DEFAULT, NO BACKFILL of historical rows by design —
-- every DROP_PENDING_PAYOUT/PAYOUT_DROP row created before this column
-- existed keeps NULL; `getDropSelfIncomes` falls back to the live
-- `projects.companyName` join for those (unchanged behaviour for rows that
-- genuinely predate the snapshot).
-- =============================================================================

ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS company_name_snapshot varchar(255);

DO $$
BEGIN
  RAISE NOTICE 'drop-obligation-company-name-snapshot: company_name_snapshot present on transactions (nullable, no backfill by design)';
END $$;
